services:
  postgres:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    ports:
      - "6379:6379"

  api-gateway:
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=*
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway:/app/api-gateway
      - ./shared:/app/shared

  user-service:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8081:8081"
      - "50051:50051"
    volumes:
      - ./user-service:/app/user-service
      - ./shared:/app/shared

  booking-service:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8082:8082"
      - "50052:50052"
    volumes:
      - ./booking-service:/app/booking-service
      - ./shared:/app/shared

  notification-service:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8083:8083"
      - "50053:50053"
    volumes:
      - ./notification-service:/app/notification-service
      - ./shared:/app/shared

  payment-service:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8084:8084"
      - "50054:50054"
    volumes:
      - ./payment-service:/app/payment-service
      - ./shared:/app/shared

  admin-service:
    environment:
      - ENVIRONMENT=development
    ports:
      - "8085:8085"
      - "50055:50055"
    volumes:
      - ./admin-service:/app/admin-service
      - ./shared:/app/shared

  # Remove nginx in development to access services directly
  nginx:
    profiles: ["production"]
