// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: admin-service/proto/admin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPendingTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortOrder     string                 `protobuf:"bytes,4,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTenantsRequest) Reset() {
	*x = GetPendingTenantsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTenantsRequest) ProtoMessage() {}

func (x *GetPendingTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTenantsRequest.ProtoReflect.Descriptor instead.
func (*GetPendingTenantsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *GetPendingTenantsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPendingTenantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPendingTenantsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *GetPendingTenantsRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

type GetPendingTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPendingTenantsResponse) Reset() {
	*x = GetPendingTenantsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingTenantsResponse) ProtoMessage() {}

func (x *GetPendingTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingTenantsResponse.ProtoReflect.Descriptor instead.
func (*GetPendingTenantsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *GetPendingTenantsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetPendingTenantsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPendingTenantsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ApproveTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TrialDays     int32                  `protobuf:"varint,2,opt,name=trial_days,json=trialDays,proto3" json:"trial_days,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	AdminId       string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTenantRequest) Reset() {
	*x = ApproveTenantRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTenantRequest) ProtoMessage() {}

func (x *ApproveTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTenantRequest.ProtoReflect.Descriptor instead.
func (*ApproveTenantRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ApproveTenantRequest) GetTrialDays() int32 {
	if x != nil {
		return x.TrialDays
	}
	return 0
}

func (x *ApproveTenantRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ApproveTenantRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ApproveTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	TrialEndDate  string                 `protobuf:"bytes,2,opt,name=trial_end_date,json=trialEndDate,proto3" json:"trial_end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApproveTenantResponse) Reset() {
	*x = ApproveTenantResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveTenantResponse) ProtoMessage() {}

func (x *ApproveTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveTenantResponse.ProtoReflect.Descriptor instead.
func (*ApproveTenantResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *ApproveTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApproveTenantResponse) GetTrialEndDate() string {
	if x != nil {
		return x.TrialEndDate
	}
	return ""
}

type RejectTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTenantRequest) Reset() {
	*x = RejectTenantRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTenantRequest) ProtoMessage() {}

func (x *RejectTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTenantRequest.ProtoReflect.Descriptor instead.
func (*RejectTenantRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *RejectTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RejectTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectTenantRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type RejectTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectTenantResponse) Reset() {
	*x = RejectTenantResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectTenantResponse) ProtoMessage() {}

func (x *RejectTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectTenantResponse.ProtoReflect.Descriptor instead.
func (*RejectTenantResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *RejectTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SuspendTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantRequest) Reset() {
	*x = SuspendTenantRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantRequest) ProtoMessage() {}

func (x *SuspendTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantRequest.ProtoReflect.Descriptor instead.
func (*SuspendTenantRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *SuspendTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SuspendTenantRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SuspendTenantRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type SuspendTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTenantResponse) Reset() {
	*x = SuspendTenantResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTenantResponse) ProtoMessage() {}

func (x *SuspendTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTenantResponse.ProtoReflect.Descriptor instead.
func (*SuspendTenantResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *SuspendTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReactivateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactivateTenantRequest) Reset() {
	*x = ReactivateTenantRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactivateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactivateTenantRequest) ProtoMessage() {}

func (x *ReactivateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactivateTenantRequest.ProtoReflect.Descriptor instead.
func (*ReactivateTenantRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{8}
}

func (x *ReactivateTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReactivateTenantRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ReactivateTenantRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type ReactivateTenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactivateTenantResponse) Reset() {
	*x = ReactivateTenantResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactivateTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactivateTenantResponse) ProtoMessage() {}

func (x *ReactivateTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactivateTenantResponse.ProtoReflect.Descriptor instead.
func (*ReactivateTenantResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ReactivateTenantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetTenantDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantDetailsRequest) Reset() {
	*x = GetTenantDetailsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantDetailsRequest) ProtoMessage() {}

func (x *GetTenantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetTenantDetailsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetTenantDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Stats         *TenantStats           `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantDetailsResponse) Reset() {
	*x = GetTenantDetailsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantDetailsResponse) ProtoMessage() {}

func (x *GetTenantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetTenantDetailsResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *GetTenantDetailsResponse) GetStats() *TenantStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type UpdateTenantTrialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AdditionalDays int32                  `protobuf:"varint,2,opt,name=additional_days,json=additionalDays,proto3" json:"additional_days,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminId        string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTenantTrialRequest) Reset() {
	*x = UpdateTenantTrialRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantTrialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantTrialRequest) ProtoMessage() {}

func (x *UpdateTenantTrialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantTrialRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantTrialRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTenantTrialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateTenantTrialRequest) GetAdditionalDays() int32 {
	if x != nil {
		return x.AdditionalDays
	}
	return 0
}

func (x *UpdateTenantTrialRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateTenantTrialRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type UpdateTenantTrialResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Message         string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	NewTrialEndDate string                 `protobuf:"bytes,2,opt,name=new_trial_end_date,json=newTrialEndDate,proto3" json:"new_trial_end_date,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTenantTrialResponse) Reset() {
	*x = UpdateTenantTrialResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantTrialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantTrialResponse) ProtoMessage() {}

func (x *UpdateTenantTrialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantTrialResponse.ProtoReflect.Descriptor instead.
func (*UpdateTenantTrialResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTenantTrialResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateTenantTrialResponse) GetNewTrialEndDate() string {
	if x != nil {
		return x.NewTrialEndDate
	}
	return ""
}

type GetPlatformStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      string                 `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformStatisticsRequest) Reset() {
	*x = GetPlatformStatisticsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformStatisticsRequest) ProtoMessage() {}

func (x *GetPlatformStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{14}
}

func (x *GetPlatformStatisticsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetPlatformStatisticsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetPlatformStatisticsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalTenants     int32                  `protobuf:"varint,1,opt,name=total_tenants,json=totalTenants,proto3" json:"total_tenants,omitempty"`
	ActiveTenants    int32                  `protobuf:"varint,2,opt,name=active_tenants,json=activeTenants,proto3" json:"active_tenants,omitempty"`
	PendingTenants   int32                  `protobuf:"varint,3,opt,name=pending_tenants,json=pendingTenants,proto3" json:"pending_tenants,omitempty"`
	SuspendedTenants int32                  `protobuf:"varint,4,opt,name=suspended_tenants,json=suspendedTenants,proto3" json:"suspended_tenants,omitempty"`
	TotalBookings    int32                  `protobuf:"varint,5,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	TotalRevenue     float64                `protobuf:"fixed64,6,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	DailyStats       []*DailyStats          `protobuf:"bytes,7,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	TenantTypeStats  []*TenantTypeStats     `protobuf:"bytes,8,rep,name=tenant_type_stats,json=tenantTypeStats,proto3" json:"tenant_type_stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPlatformStatisticsResponse) Reset() {
	*x = GetPlatformStatisticsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformStatisticsResponse) ProtoMessage() {}

func (x *GetPlatformStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{15}
}

func (x *GetPlatformStatisticsResponse) GetTotalTenants() int32 {
	if x != nil {
		return x.TotalTenants
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetActiveTenants() int32 {
	if x != nil {
		return x.ActiveTenants
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetPendingTenants() int32 {
	if x != nil {
		return x.PendingTenants
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetSuspendedTenants() int32 {
	if x != nil {
		return x.SuspendedTenants
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetTotalBookings() int32 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetPlatformStatisticsResponse) GetDailyStats() []*DailyStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

func (x *GetPlatformStatisticsResponse) GetTenantTypeStats() []*TenantTypeStats {
	if x != nil {
		return x.TenantTypeStats
	}
	return nil
}

type GetTenantStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantStatisticsRequest) Reset() {
	*x = GetTenantStatisticsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantStatisticsRequest) ProtoMessage() {}

func (x *GetTenantStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetTenantStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{16}
}

func (x *GetTenantStatisticsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantStatisticsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetTenantStatisticsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetTenantStatisticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *TenantStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantStatisticsResponse) Reset() {
	*x = GetTenantStatisticsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantStatisticsResponse) ProtoMessage() {}

func (x *GetTenantStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetTenantStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{17}
}

func (x *GetTenantStatisticsResponse) GetStats() *TenantStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetSystemHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemHealthRequest) Reset() {
	*x = GetSystemHealthRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemHealthRequest) ProtoMessage() {}

func (x *GetSystemHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemHealthRequest.ProtoReflect.Descriptor instead.
func (*GetSystemHealthRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{18}
}

type GetSystemHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallStatus string                 `protobuf:"bytes,1,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	Services      []*ServiceHealth       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	Metrics       *SystemMetrics         `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	LastCheck     string                 `protobuf:"bytes,4,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemHealthResponse) Reset() {
	*x = GetSystemHealthResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemHealthResponse) ProtoMessage() {}

func (x *GetSystemHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemHealthResponse.ProtoReflect.Descriptor instead.
func (*GetSystemHealthResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetSystemHealthResponse) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *GetSystemHealthResponse) GetServices() []*ServiceHealth {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetSystemHealthResponse) GetMetrics() *SystemMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetSystemHealthResponse) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

type GetSystemLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemLogsRequest) Reset() {
	*x = GetSystemLogsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemLogsRequest) ProtoMessage() {}

func (x *GetSystemLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemLogsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemLogsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{20}
}

func (x *GetSystemLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *GetSystemLogsRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetSystemLogsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetSystemLogsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetSystemLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSystemLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSystemLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*LogEntry            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemLogsResponse) Reset() {
	*x = GetSystemLogsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemLogsResponse) ProtoMessage() {}

func (x *GetSystemLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemLogsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemLogsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{21}
}

func (x *GetSystemLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetSystemLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetSystemLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetSystemLogsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetActiveUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Minutes       int32                  `protobuf:"varint,2,opt,name=minutes,proto3" json:"minutes,omitempty"` // active in last N minutes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveUsersRequest) Reset() {
	*x = GetActiveUsersRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveUsersRequest) ProtoMessage() {}

func (x *GetActiveUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveUsersRequest.ProtoReflect.Descriptor instead.
func (*GetActiveUsersRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{22}
}

func (x *GetActiveUsersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetActiveUsersRequest) GetMinutes() int32 {
	if x != nil {
		return x.Minutes
	}
	return 0
}

type GetActiveUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalActive   int32                  `protobuf:"varint,1,opt,name=total_active,json=totalActive,proto3" json:"total_active,omitempty"`
	Users         []*ActiveUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveUsersResponse) Reset() {
	*x = GetActiveUsersResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveUsersResponse) ProtoMessage() {}

func (x *GetActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*GetActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{23}
}

func (x *GetActiveUsersResponse) GetTotalActive() int32 {
	if x != nil {
		return x.TotalActive
	}
	return 0
}

func (x *GetActiveUsersResponse) GetUsers() []*ActiveUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetSystemMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricType    string                 `protobuf:"bytes,1,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsRequest) Reset() {
	*x = GetSystemMetricsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsRequest) ProtoMessage() {}

func (x *GetSystemMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetSystemMetricsRequest) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

func (x *GetSystemMetricsRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

type GetSystemMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*MetricPoint         `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemMetricsResponse) Reset() {
	*x = GetSystemMetricsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemMetricsResponse) ProtoMessage() {}

func (x *GetSystemMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemMetricsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GetSystemMetricsResponse) GetMetrics() []*MetricPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type BulkUpdateTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantIds     []string               `protobuf:"bytes,1,rep,name=tenant_ids,json=tenantIds,proto3" json:"tenant_ids,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // approve, suspend, reactivate, extend_trial
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AdminId       string                 `protobuf:"bytes,4,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkUpdateTenantsRequest) Reset() {
	*x = BulkUpdateTenantsRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateTenantsRequest) ProtoMessage() {}

func (x *BulkUpdateTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateTenantsRequest.ProtoReflect.Descriptor instead.
func (*BulkUpdateTenantsRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{26}
}

func (x *BulkUpdateTenantsRequest) GetTenantIds() []string {
	if x != nil {
		return x.TenantIds
	}
	return nil
}

func (x *BulkUpdateTenantsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BulkUpdateTenantsRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *BulkUpdateTenantsRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type BulkUpdateTenantsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount    int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	FailedTenantIds []string               `protobuf:"bytes,2,rep,name=failed_tenant_ids,json=failedTenantIds,proto3" json:"failed_tenant_ids,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BulkUpdateTenantsResponse) Reset() {
	*x = BulkUpdateTenantsResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkUpdateTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkUpdateTenantsResponse) ProtoMessage() {}

func (x *BulkUpdateTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkUpdateTenantsResponse.ProtoReflect.Descriptor instead.
func (*BulkUpdateTenantsResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{27}
}

func (x *BulkUpdateTenantsResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *BulkUpdateTenantsResponse) GetFailedTenantIds() []string {
	if x != nil {
		return x.FailedTenantIds
	}
	return nil
}

func (x *BulkUpdateTenantsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExportDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      string                 `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // tenants, bookings, users
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`                     // csv, json, xlsx
	DateFrom      string                 `protobuf:"bytes,3,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,4,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Filters       []string               `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataRequest) Reset() {
	*x = ExportDataRequest{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataRequest) ProtoMessage() {}

func (x *ExportDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataRequest.ProtoReflect.Descriptor instead.
func (*ExportDataRequest) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ExportDataRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *ExportDataRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportDataRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ExportDataRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *ExportDataRequest) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ExportDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadUrl   string                 `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ExpiresAt     string                 `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportDataResponse) Reset() {
	*x = ExportDataResponse{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportDataResponse) ProtoMessage() {}

func (x *ExportDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportDataResponse.ProtoReflect.Descriptor instead.
func (*ExportDataResponse) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{29}
}

func (x *ExportDataResponse) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *ExportDataResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportDataResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type Tenant struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BusinessName        string                 `protobuf:"bytes,2,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessType        string                 `protobuf:"bytes,3,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Subdomain           string                 `protobuf:"bytes,4,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Timezone            string                 `protobuf:"bytes,5,opt,name=timezone,proto3" json:"timezone,omitempty"`
	OwnerId             string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Status              string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TrialStartDate      string                 `protobuf:"bytes,8,opt,name=trial_start_date,json=trialStartDate,proto3" json:"trial_start_date,omitempty"`
	TrialEndDate        string                 `protobuf:"bytes,9,opt,name=trial_end_date,json=trialEndDate,proto3" json:"trial_end_date,omitempty"`
	SubscriptionEndDate string                 `protobuf:"bytes,10,opt,name=subscription_end_date,json=subscriptionEndDate,proto3" json:"subscription_end_date,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Owner               *Owner                 `protobuf:"bytes,13,opt,name=owner,proto3" json:"owner,omitempty"`
	LocationsCount      int32                  `protobuf:"varint,14,opt,name=locations_count,json=locationsCount,proto3" json:"locations_count,omitempty"`
	MastersCount        int32                  `protobuf:"varint,15,opt,name=masters_count,json=mastersCount,proto3" json:"masters_count,omitempty"`
	ServicesCount       int32                  `protobuf:"varint,16,opt,name=services_count,json=servicesCount,proto3" json:"services_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{30}
}

func (x *Tenant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tenant) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *Tenant) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *Tenant) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *Tenant) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Tenant) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Tenant) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tenant) GetTrialStartDate() string {
	if x != nil {
		return x.TrialStartDate
	}
	return ""
}

func (x *Tenant) GetTrialEndDate() string {
	if x != nil {
		return x.TrialEndDate
	}
	return ""
}

func (x *Tenant) GetSubscriptionEndDate() string {
	if x != nil {
		return x.SubscriptionEndDate
	}
	return ""
}

func (x *Tenant) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Tenant) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Tenant) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Tenant) GetLocationsCount() int32 {
	if x != nil {
		return x.LocationsCount
	}
	return 0
}

func (x *Tenant) GetMastersCount() int32 {
	if x != nil {
		return x.MastersCount
	}
	return 0
}

func (x *Tenant) GetServicesCount() int32 {
	if x != nil {
		return x.ServicesCount
	}
	return 0
}

type Owner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	LastLogin     string                 `protobuf:"bytes,6,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Owner) Reset() {
	*x = Owner{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Owner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Owner) ProtoMessage() {}

func (x *Owner) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Owner.ProtoReflect.Descriptor instead.
func (*Owner) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{31}
}

func (x *Owner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Owner) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Owner) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Owner) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Owner) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Owner) GetLastLogin() string {
	if x != nil {
		return x.LastLogin
	}
	return ""
}

type TenantStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalBookings         int32                  `protobuf:"varint,1,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	CompletedBookings     int32                  `protobuf:"varint,2,opt,name=completed_bookings,json=completedBookings,proto3" json:"completed_bookings,omitempty"`
	CancelledBookings     int32                  `protobuf:"varint,3,opt,name=cancelled_bookings,json=cancelledBookings,proto3" json:"cancelled_bookings,omitempty"`
	TotalRevenue          float64                `protobuf:"fixed64,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AvgBookingValue       float64                `protobuf:"fixed64,5,opt,name=avg_booking_value,json=avgBookingValue,proto3" json:"avg_booking_value,omitempty"`
	TotalClients          int32                  `protobuf:"varint,6,opt,name=total_clients,json=totalClients,proto3" json:"total_clients,omitempty"`
	ActiveMasters         int32                  `protobuf:"varint,7,opt,name=active_masters,json=activeMasters,proto3" json:"active_masters,omitempty"`
	MostPopularService    string                 `protobuf:"bytes,8,opt,name=most_popular_service,json=mostPopularService,proto3" json:"most_popular_service,omitempty"`
	CustomerRetentionRate float64                `protobuf:"fixed64,9,opt,name=customer_retention_rate,json=customerRetentionRate,proto3" json:"customer_retention_rate,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TenantStats) Reset() {
	*x = TenantStats{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantStats) ProtoMessage() {}

func (x *TenantStats) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantStats.ProtoReflect.Descriptor instead.
func (*TenantStats) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{32}
}

func (x *TenantStats) GetTotalBookings() int32 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *TenantStats) GetCompletedBookings() int32 {
	if x != nil {
		return x.CompletedBookings
	}
	return 0
}

func (x *TenantStats) GetCancelledBookings() int32 {
	if x != nil {
		return x.CancelledBookings
	}
	return 0
}

func (x *TenantStats) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *TenantStats) GetAvgBookingValue() float64 {
	if x != nil {
		return x.AvgBookingValue
	}
	return 0
}

func (x *TenantStats) GetTotalClients() int32 {
	if x != nil {
		return x.TotalClients
	}
	return 0
}

func (x *TenantStats) GetActiveMasters() int32 {
	if x != nil {
		return x.ActiveMasters
	}
	return 0
}

func (x *TenantStats) GetMostPopularService() string {
	if x != nil {
		return x.MostPopularService
	}
	return ""
}

func (x *TenantStats) GetCustomerRetentionRate() float64 {
	if x != nil {
		return x.CustomerRetentionRate
	}
	return 0
}

type DailyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	NewTenants    int32                  `protobuf:"varint,2,opt,name=new_tenants,json=newTenants,proto3" json:"new_tenants,omitempty"`
	TotalBookings int32                  `protobuf:"varint,3,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	Revenue       float64                `protobuf:"fixed64,4,opt,name=revenue,proto3" json:"revenue,omitempty"`
	ActiveUsers   int32                  `protobuf:"varint,5,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{33}
}

func (x *DailyStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStats) GetNewTenants() int32 {
	if x != nil {
		return x.NewTenants
	}
	return 0
}

func (x *DailyStats) GetTotalBookings() int32 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *DailyStats) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *DailyStats) GetActiveUsers() int32 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

type TenantTypeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessType  string                 `protobuf:"bytes,1,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantTypeStats) Reset() {
	*x = TenantTypeStats{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantTypeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantTypeStats) ProtoMessage() {}

func (x *TenantTypeStats) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantTypeStats.ProtoReflect.Descriptor instead.
func (*TenantTypeStats) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{34}
}

func (x *TenantTypeStats) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *TenantTypeStats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *TenantTypeStats) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type ServiceHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // healthy, warning, critical
	LastCheck     string                 `protobuf:"bytes,3,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"`
	ResponseTime  string                 `protobuf:"bytes,4,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceHealth) Reset() {
	*x = ServiceHealth{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHealth) ProtoMessage() {}

func (x *ServiceHealth) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHealth.ProtoReflect.Descriptor instead.
func (*ServiceHealth) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{35}
}

func (x *ServiceHealth) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceHealth) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

func (x *ServiceHealth) GetResponseTime() string {
	if x != nil {
		return x.ResponseTime
	}
	return ""
}

func (x *ServiceHealth) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SystemMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage          float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage       float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage         float64                `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	ResponseTime      float64                `protobuf:"fixed64,5,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"`
	ErrorRate         int32                  `protobuf:"varint,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{36}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *SystemMetrics) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SystemMetrics) GetResponseTime() float64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *SystemMetrics) GetErrorRate() int32 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{37}
}

func (x *LogEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ActiveUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LastActivity  string                 `protobuf:"bytes,5,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveUser) Reset() {
	*x = ActiveUser{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUser) ProtoMessage() {}

func (x *ActiveUser) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUser.ProtoReflect.Descriptor instead.
func (*ActiveUser) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{38}
}

func (x *ActiveUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ActiveUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActiveUser) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ActiveUser) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ActiveUser) GetLastActivity() string {
	if x != nil {
		return x.LastActivity
	}
	return ""
}

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_admin_service_proto_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_admin_service_proto_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_admin_service_proto_admin_proto_rawDescGZIP(), []int{39}
}

func (x *MetricPoint) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_admin_service_proto_admin_proto protoreflect.FileDescriptor

const file_admin_service_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x1fadmin-service/proto/admin.proto\x12\x05admin\"|\n" +
	"\x18GetPendingTenantsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x17\n" +
	"\asort_by\x18\x03 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x04 \x01(\tR\tsortOrder\"\x84\x01\n" +
	"\x19GetPendingTenantsResponse\x12'\n" +
	"\atenants\x18\x01 \x03(\v2\r.admin.TenantR\atenants\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x14ApproveTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"trial_days\x18\x02 \x01(\x05R\ttrialDays\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\"W\n" +
	"\x15ApproveTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12$\n" +
	"\x0etrial_end_date\x18\x02 \x01(\tR\ftrialEndDate\"e\n" +
	"\x13RejectTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"0\n" +
	"\x14RejectTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"f\n" +
	"\x14SuspendTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"1\n" +
	"\x15SuspendTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"g\n" +
	"\x17ReactivateTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"4\n" +
	"\x18ReactivateTenantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x17GetTenantDetailsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"k\n" +
	"\x18GetTenantDetailsResponse\x12%\n" +
	"\x06tenant\x18\x01 \x01(\v2\r.admin.TenantR\x06tenant\x12(\n" +
	"\x05stats\x18\x02 \x01(\v2\x12.admin.TenantStatsR\x05stats\"\x93\x01\n" +
	"\x18UpdateTenantTrialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fadditional_days\x18\x02 \x01(\x05R\x0eadditionalDays\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\"b\n" +
	"\x19UpdateTenantTrialResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12+\n" +
	"\x12new_trial_end_date\x18\x02 \x01(\tR\x0fnewTrialEndDate\"T\n" +
	"\x1cGetPlatformStatisticsRequest\x12\x1b\n" +
	"\tdate_from\x18\x01 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x02 \x01(\tR\x06dateTo\"\x85\x03\n" +
	"\x1dGetPlatformStatisticsResponse\x12#\n" +
	"\rtotal_tenants\x18\x01 \x01(\x05R\ftotalTenants\x12%\n" +
	"\x0eactive_tenants\x18\x02 \x01(\x05R\ractiveTenants\x12'\n" +
	"\x0fpending_tenants\x18\x03 \x01(\x05R\x0ependingTenants\x12+\n" +
	"\x11suspended_tenants\x18\x04 \x01(\x05R\x10suspendedTenants\x12%\n" +
	"\x0etotal_bookings\x18\x05 \x01(\x05R\rtotalBookings\x12#\n" +
	"\rtotal_revenue\x18\x06 \x01(\x01R\ftotalRevenue\x122\n" +
	"\vdaily_stats\x18\a \x03(\v2\x11.admin.DailyStatsR\n" +
	"dailyStats\x12B\n" +
	"\x11tenant_type_stats\x18\b \x03(\v2\x16.admin.TenantTypeStatsR\x0ftenantTypeStats\"o\n" +
	"\x1aGetTenantStatisticsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\"G\n" +
	"\x1bGetTenantStatisticsResponse\x12(\n" +
	"\x05stats\x18\x01 \x01(\v2\x12.admin.TenantStatsR\x05stats\"\x18\n" +
	"\x16GetSystemHealthRequest\"\xc1\x01\n" +
	"\x17GetSystemHealthResponse\x12%\n" +
	"\x0eoverall_status\x18\x01 \x01(\tR\roverallStatus\x120\n" +
	"\bservices\x18\x02 \x03(\v2\x14.admin.ServiceHealthR\bservices\x12.\n" +
	"\ametrics\x18\x03 \x01(\v2\x14.admin.SystemMetricsR\ametrics\x12\x1d\n" +
	"\n" +
	"last_check\x18\x04 \x01(\tR\tlastCheck\"\xa6\x01\n" +
	"\x14GetSystemLogsRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1b\n" +
	"\tdate_from\x18\x03 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x04 \x01(\tR\x06dateTo\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"|\n" +
	"\x15GetSystemLogsResponse\x12#\n" +
	"\x04logs\x18\x01 \x03(\v2\x0f.admin.LogEntryR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"N\n" +
	"\x15GetActiveUsersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\aminutes\x18\x02 \x01(\x05R\aminutes\"d\n" +
	"\x16GetActiveUsersResponse\x12!\n" +
	"\ftotal_active\x18\x01 \x01(\x05R\vtotalActive\x12'\n" +
	"\x05users\x18\x02 \x03(\v2\x11.admin.ActiveUserR\x05users\"Y\n" +
	"\x17GetSystemMetricsRequest\x12\x1f\n" +
	"\vmetric_type\x18\x01 \x01(\tR\n" +
	"metricType\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\"H\n" +
	"\x18GetSystemMetricsResponse\x12,\n" +
	"\ametrics\x18\x01 \x03(\v2\x12.admin.MetricPointR\ametrics\"\xfc\x01\n" +
	"\x18BulkUpdateTenantsRequest\x12\x1d\n" +
	"\n" +
	"tenant_ids\x18\x01 \x03(\tR\ttenantIds\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12O\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2/.admin.BulkUpdateTenantsRequest.ParametersEntryR\n" +
	"parameters\x12\x19\n" +
	"\badmin_id\x18\x04 \x01(\tR\aadminId\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x19BulkUpdateTenantsResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12*\n" +
	"\x11failed_tenant_ids\x18\x02 \x03(\tR\x0ffailedTenantIds\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x98\x01\n" +
	"\x11ExportDataRequest\x12\x1b\n" +
	"\tdata_type\x18\x01 \x01(\tR\bdataType\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x1b\n" +
	"\tdate_from\x18\x03 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x04 \x01(\tR\x06dateTo\x12\x18\n" +
	"\afilters\x18\x05 \x03(\tR\afilters\"s\n" +
	"\x12ExportDataResponse\x12!\n" +
	"\fdownload_url\x18\x01 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\tR\texpiresAt\"\xaa\x04\n" +
	"\x06Tenant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rbusiness_name\x18\x02 \x01(\tR\fbusinessName\x12#\n" +
	"\rbusiness_type\x18\x03 \x01(\tR\fbusinessType\x12\x1c\n" +
	"\tsubdomain\x18\x04 \x01(\tR\tsubdomain\x12\x1a\n" +
	"\btimezone\x18\x05 \x01(\tR\btimezone\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12(\n" +
	"\x10trial_start_date\x18\b \x01(\tR\x0etrialStartDate\x12$\n" +
	"\x0etrial_end_date\x18\t \x01(\tR\ftrialEndDate\x122\n" +
	"\x15subscription_end_date\x18\n" +
	" \x01(\tR\x13subscriptionEndDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x12\"\n" +
	"\x05owner\x18\r \x01(\v2\f.admin.OwnerR\x05owner\x12'\n" +
	"\x0flocations_count\x18\x0e \x01(\x05R\x0elocationsCount\x12#\n" +
	"\rmasters_count\x18\x0f \x01(\x05R\fmastersCount\x12%\n" +
	"\x0eservices_count\x18\x10 \x01(\x05R\rservicesCount\"\x9e\x01\n" +
	"\x05Owner\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"last_login\x18\x06 \x01(\tR\tlastLogin\"\x99\x03\n" +
	"\vTenantStats\x12%\n" +
	"\x0etotal_bookings\x18\x01 \x01(\x05R\rtotalBookings\x12-\n" +
	"\x12completed_bookings\x18\x02 \x01(\x05R\x11completedBookings\x12-\n" +
	"\x12cancelled_bookings\x18\x03 \x01(\x05R\x11cancelledBookings\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x01R\ftotalRevenue\x12*\n" +
	"\x11avg_booking_value\x18\x05 \x01(\x01R\x0favgBookingValue\x12#\n" +
	"\rtotal_clients\x18\x06 \x01(\x05R\ftotalClients\x12%\n" +
	"\x0eactive_masters\x18\a \x01(\x05R\ractiveMasters\x120\n" +
	"\x14most_popular_service\x18\b \x01(\tR\x12mostPopularService\x126\n" +
	"\x17customer_retention_rate\x18\t \x01(\x01R\x15customerRetentionRate\"\xa5\x01\n" +
	"\n" +
	"DailyStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x1f\n" +
	"\vnew_tenants\x18\x02 \x01(\x05R\n" +
	"newTenants\x12%\n" +
	"\x0etotal_bookings\x18\x03 \x01(\x05R\rtotalBookings\x12\x18\n" +
	"\arevenue\x18\x04 \x01(\x01R\arevenue\x12!\n" +
	"\factive_users\x18\x05 \x01(\x05R\vactiveUsers\"l\n" +
	"\x0fTenantTypeStats\x12#\n" +
	"\rbusiness_type\x18\x01 \x01(\tR\fbusinessType\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"\xb3\x01\n" +
	"\rServiceHealth\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"last_check\x18\x03 \x01(\tR\tlastCheck\x12#\n" +
	"\rresponse_time\x18\x04 \x01(\tR\fresponseTime\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"\xe1\x01\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x03 \x01(\x01R\tdiskUsage\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x12#\n" +
	"\rresponse_time\x18\x05 \x01(\x01R\fresponseTime\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x05R\terrorRate\"\xfa\x01\n" +
	"\bLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\x129\n" +
	"\bmetadata\x18\x06 \x03(\v2\x1d.admin.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x91\x01\n" +
	"\n" +
	"ActiveUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12#\n" +
	"\rlast_activity\x18\x05 \x01(\tR\flastActivity\"\xb4\x01\n" +
	"\vMetricPoint\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x126\n" +
	"\x06labels\x18\x03 \x03(\v2\x1e.admin.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xe8\t\n" +
	"\fAdminService\x12V\n" +
	"\x11GetPendingTenants\x12\x1f.admin.GetPendingTenantsRequest\x1a .admin.GetPendingTenantsResponse\x12J\n" +
	"\rApproveTenant\x12\x1b.admin.ApproveTenantRequest\x1a\x1c.admin.ApproveTenantResponse\x12G\n" +
	"\fRejectTenant\x12\x1a.admin.RejectTenantRequest\x1a\x1b.admin.RejectTenantResponse\x12J\n" +
	"\rSuspendTenant\x12\x1b.admin.SuspendTenantRequest\x1a\x1c.admin.SuspendTenantResponse\x12S\n" +
	"\x10ReactivateTenant\x12\x1e.admin.ReactivateTenantRequest\x1a\x1f.admin.ReactivateTenantResponse\x12S\n" +
	"\x10GetTenantDetails\x12\x1e.admin.GetTenantDetailsRequest\x1a\x1f.admin.GetTenantDetailsResponse\x12V\n" +
	"\x11UpdateTenantTrial\x12\x1f.admin.UpdateTenantTrialRequest\x1a .admin.UpdateTenantTrialResponse\x12b\n" +
	"\x15GetPlatformStatistics\x12#.admin.GetPlatformStatisticsRequest\x1a$.admin.GetPlatformStatisticsResponse\x12\\\n" +
	"\x13GetTenantStatistics\x12!.admin.GetTenantStatisticsRequest\x1a\".admin.GetTenantStatisticsResponse\x12P\n" +
	"\x0fGetSystemHealth\x12\x1d.admin.GetSystemHealthRequest\x1a\x1e.admin.GetSystemHealthResponse\x12J\n" +
	"\rGetSystemLogs\x12\x1b.admin.GetSystemLogsRequest\x1a\x1c.admin.GetSystemLogsResponse\x12M\n" +
	"\x0eGetActiveUsers\x12\x1c.admin.GetActiveUsersRequest\x1a\x1d.admin.GetActiveUsersResponse\x12S\n" +
	"\x10GetSystemMetrics\x12\x1e.admin.GetSystemMetricsRequest\x1a\x1f.admin.GetSystemMetricsResponse\x12V\n" +
	"\x11BulkUpdateTenants\x12\x1f.admin.BulkUpdateTenantsRequest\x1a .admin.BulkUpdateTenantsResponse\x12A\n" +
	"\n" +
	"ExportData\x12\x18.admin.ExportDataRequest\x1a\x19.admin.ExportDataResponseB&Z$booking-platform/admin-service/protob\x06proto3"

var (
	file_admin_service_proto_admin_proto_rawDescOnce sync.Once
	file_admin_service_proto_admin_proto_rawDescData []byte
)

func file_admin_service_proto_admin_proto_rawDescGZIP() []byte {
	file_admin_service_proto_admin_proto_rawDescOnce.Do(func() {
		file_admin_service_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_admin_service_proto_admin_proto_rawDesc), len(file_admin_service_proto_admin_proto_rawDesc)))
	})
	return file_admin_service_proto_admin_proto_rawDescData
}

var file_admin_service_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_admin_service_proto_admin_proto_goTypes = []any{
	(*GetPendingTenantsRequest)(nil),      // 0: admin.GetPendingTenantsRequest
	(*GetPendingTenantsResponse)(nil),     // 1: admin.GetPendingTenantsResponse
	(*ApproveTenantRequest)(nil),          // 2: admin.ApproveTenantRequest
	(*ApproveTenantResponse)(nil),         // 3: admin.ApproveTenantResponse
	(*RejectTenantRequest)(nil),           // 4: admin.RejectTenantRequest
	(*RejectTenantResponse)(nil),          // 5: admin.RejectTenantResponse
	(*SuspendTenantRequest)(nil),          // 6: admin.SuspendTenantRequest
	(*SuspendTenantResponse)(nil),         // 7: admin.SuspendTenantResponse
	(*ReactivateTenantRequest)(nil),       // 8: admin.ReactivateTenantRequest
	(*ReactivateTenantResponse)(nil),      // 9: admin.ReactivateTenantResponse
	(*GetTenantDetailsRequest)(nil),       // 10: admin.GetTenantDetailsRequest
	(*GetTenantDetailsResponse)(nil),      // 11: admin.GetTenantDetailsResponse
	(*UpdateTenantTrialRequest)(nil),      // 12: admin.UpdateTenantTrialRequest
	(*UpdateTenantTrialResponse)(nil),     // 13: admin.UpdateTenantTrialResponse
	(*GetPlatformStatisticsRequest)(nil),  // 14: admin.GetPlatformStatisticsRequest
	(*GetPlatformStatisticsResponse)(nil), // 15: admin.GetPlatformStatisticsResponse
	(*GetTenantStatisticsRequest)(nil),    // 16: admin.GetTenantStatisticsRequest
	(*GetTenantStatisticsResponse)(nil),   // 17: admin.GetTenantStatisticsResponse
	(*GetSystemHealthRequest)(nil),        // 18: admin.GetSystemHealthRequest
	(*GetSystemHealthResponse)(nil),       // 19: admin.GetSystemHealthResponse
	(*GetSystemLogsRequest)(nil),          // 20: admin.GetSystemLogsRequest
	(*GetSystemLogsResponse)(nil),         // 21: admin.GetSystemLogsResponse
	(*GetActiveUsersRequest)(nil),         // 22: admin.GetActiveUsersRequest
	(*GetActiveUsersResponse)(nil),        // 23: admin.GetActiveUsersResponse
	(*GetSystemMetricsRequest)(nil),       // 24: admin.GetSystemMetricsRequest
	(*GetSystemMetricsResponse)(nil),      // 25: admin.GetSystemMetricsResponse
	(*BulkUpdateTenantsRequest)(nil),      // 26: admin.BulkUpdateTenantsRequest
	(*BulkUpdateTenantsResponse)(nil),     // 27: admin.BulkUpdateTenantsResponse
	(*ExportDataRequest)(nil),             // 28: admin.ExportDataRequest
	(*ExportDataResponse)(nil),            // 29: admin.ExportDataResponse
	(*Tenant)(nil),                        // 30: admin.Tenant
	(*Owner)(nil),                         // 31: admin.Owner
	(*TenantStats)(nil),                   // 32: admin.TenantStats
	(*DailyStats)(nil),                    // 33: admin.DailyStats
	(*TenantTypeStats)(nil),               // 34: admin.TenantTypeStats
	(*ServiceHealth)(nil),                 // 35: admin.ServiceHealth
	(*SystemMetrics)(nil),                 // 36: admin.SystemMetrics
	(*LogEntry)(nil),                      // 37: admin.LogEntry
	(*ActiveUser)(nil),                    // 38: admin.ActiveUser
	(*MetricPoint)(nil),                   // 39: admin.MetricPoint
	nil,                                   // 40: admin.BulkUpdateTenantsRequest.ParametersEntry
	nil,                                   // 41: admin.LogEntry.MetadataEntry
	nil,                                   // 42: admin.MetricPoint.LabelsEntry
}
var file_admin_service_proto_admin_proto_depIdxs = []int32{
	30, // 0: admin.GetPendingTenantsResponse.tenants:type_name -> admin.Tenant
	30, // 1: admin.GetTenantDetailsResponse.tenant:type_name -> admin.Tenant
	32, // 2: admin.GetTenantDetailsResponse.stats:type_name -> admin.TenantStats
	33, // 3: admin.GetPlatformStatisticsResponse.daily_stats:type_name -> admin.DailyStats
	34, // 4: admin.GetPlatformStatisticsResponse.tenant_type_stats:type_name -> admin.TenantTypeStats
	32, // 5: admin.GetTenantStatisticsResponse.stats:type_name -> admin.TenantStats
	35, // 6: admin.GetSystemHealthResponse.services:type_name -> admin.ServiceHealth
	36, // 7: admin.GetSystemHealthResponse.metrics:type_name -> admin.SystemMetrics
	37, // 8: admin.GetSystemLogsResponse.logs:type_name -> admin.LogEntry
	38, // 9: admin.GetActiveUsersResponse.users:type_name -> admin.ActiveUser
	39, // 10: admin.GetSystemMetricsResponse.metrics:type_name -> admin.MetricPoint
	40, // 11: admin.BulkUpdateTenantsRequest.parameters:type_name -> admin.BulkUpdateTenantsRequest.ParametersEntry
	31, // 12: admin.Tenant.owner:type_name -> admin.Owner
	41, // 13: admin.LogEntry.metadata:type_name -> admin.LogEntry.MetadataEntry
	42, // 14: admin.MetricPoint.labels:type_name -> admin.MetricPoint.LabelsEntry
	0,  // 15: admin.AdminService.GetPendingTenants:input_type -> admin.GetPendingTenantsRequest
	2,  // 16: admin.AdminService.ApproveTenant:input_type -> admin.ApproveTenantRequest
	4,  // 17: admin.AdminService.RejectTenant:input_type -> admin.RejectTenantRequest
	6,  // 18: admin.AdminService.SuspendTenant:input_type -> admin.SuspendTenantRequest
	8,  // 19: admin.AdminService.ReactivateTenant:input_type -> admin.ReactivateTenantRequest
	10, // 20: admin.AdminService.GetTenantDetails:input_type -> admin.GetTenantDetailsRequest
	12, // 21: admin.AdminService.UpdateTenantTrial:input_type -> admin.UpdateTenantTrialRequest
	14, // 22: admin.AdminService.GetPlatformStatistics:input_type -> admin.GetPlatformStatisticsRequest
	16, // 23: admin.AdminService.GetTenantStatistics:input_type -> admin.GetTenantStatisticsRequest
	18, // 24: admin.AdminService.GetSystemHealth:input_type -> admin.GetSystemHealthRequest
	20, // 25: admin.AdminService.GetSystemLogs:input_type -> admin.GetSystemLogsRequest
	22, // 26: admin.AdminService.GetActiveUsers:input_type -> admin.GetActiveUsersRequest
	24, // 27: admin.AdminService.GetSystemMetrics:input_type -> admin.GetSystemMetricsRequest
	26, // 28: admin.AdminService.BulkUpdateTenants:input_type -> admin.BulkUpdateTenantsRequest
	28, // 29: admin.AdminService.ExportData:input_type -> admin.ExportDataRequest
	1,  // 30: admin.AdminService.GetPendingTenants:output_type -> admin.GetPendingTenantsResponse
	3,  // 31: admin.AdminService.ApproveTenant:output_type -> admin.ApproveTenantResponse
	5,  // 32: admin.AdminService.RejectTenant:output_type -> admin.RejectTenantResponse
	7,  // 33: admin.AdminService.SuspendTenant:output_type -> admin.SuspendTenantResponse
	9,  // 34: admin.AdminService.ReactivateTenant:output_type -> admin.ReactivateTenantResponse
	11, // 35: admin.AdminService.GetTenantDetails:output_type -> admin.GetTenantDetailsResponse
	13, // 36: admin.AdminService.UpdateTenantTrial:output_type -> admin.UpdateTenantTrialResponse
	15, // 37: admin.AdminService.GetPlatformStatistics:output_type -> admin.GetPlatformStatisticsResponse
	17, // 38: admin.AdminService.GetTenantStatistics:output_type -> admin.GetTenantStatisticsResponse
	19, // 39: admin.AdminService.GetSystemHealth:output_type -> admin.GetSystemHealthResponse
	21, // 40: admin.AdminService.GetSystemLogs:output_type -> admin.GetSystemLogsResponse
	23, // 41: admin.AdminService.GetActiveUsers:output_type -> admin.GetActiveUsersResponse
	25, // 42: admin.AdminService.GetSystemMetrics:output_type -> admin.GetSystemMetricsResponse
	27, // 43: admin.AdminService.BulkUpdateTenants:output_type -> admin.BulkUpdateTenantsResponse
	29, // 44: admin.AdminService.ExportData:output_type -> admin.ExportDataResponse
	30, // [30:45] is the sub-list for method output_type
	15, // [15:30] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_admin_service_proto_admin_proto_init() }
func file_admin_service_proto_admin_proto_init() {
	if File_admin_service_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_admin_service_proto_admin_proto_rawDesc), len(file_admin_service_proto_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_admin_service_proto_admin_proto_goTypes,
		DependencyIndexes: file_admin_service_proto_admin_proto_depIdxs,
		MessageInfos:      file_admin_service_proto_admin_proto_msgTypes,
	}.Build()
	File_admin_service_proto_admin_proto = out.File
	file_admin_service_proto_admin_proto_goTypes = nil
	file_admin_service_proto_admin_proto_depIdxs = nil
}
