// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: user-service/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	User          *User                  `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterBusinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessName  string                 `protobuf:"bytes,1,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Subdomain     string                 `protobuf:"bytes,3,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`
	OwnerEmail    string                 `protobuf:"bytes,5,opt,name=owner_email,json=ownerEmail,proto3" json:"owner_email,omitempty"`
	OwnerPhone    string                 `protobuf:"bytes,6,opt,name=owner_phone,json=ownerPhone,proto3" json:"owner_phone,omitempty"`
	OwnerName     string                 `protobuf:"bytes,7,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBusinessRequest) Reset() {
	*x = RegisterBusinessRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBusinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBusinessRequest) ProtoMessage() {}

func (x *RegisterBusinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBusinessRequest.ProtoReflect.Descriptor instead.
func (*RegisterBusinessRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBusinessRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *RegisterBusinessRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *RegisterBusinessRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *RegisterBusinessRequest) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *RegisterBusinessRequest) GetOwnerEmail() string {
	if x != nil {
		return x.OwnerEmail
	}
	return ""
}

func (x *RegisterBusinessRequest) GetOwnerPhone() string {
	if x != nil {
		return x.OwnerPhone
	}
	return ""
}

func (x *RegisterBusinessRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type RegisterBusinessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBusinessResponse) Reset() {
	*x = RegisterBusinessResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBusinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBusinessResponse) ProtoMessage() {}

func (x *RegisterBusinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBusinessResponse.ProtoReflect.Descriptor instead.
func (*RegisterBusinessResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterBusinessResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterBusinessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	EmailVerified bool                   `protobuf:"varint,10,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	PhoneVerified bool                   `protobuf:"varint,11,opt,name=phone_verified,json=phoneVerified,proto3" json:"phone_verified,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_service_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *User) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

func (x *User) GetPhoneVerified() bool {
	if x != nil {
		return x.PhoneVerified
	}
	return false
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateClientSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientSessionRequest) Reset() {
	*x = CreateClientSessionRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientSessionRequest) ProtoMessage() {}

func (x *CreateClientSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateClientSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateClientSessionRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateClientSessionRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateClientSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateClientSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientSessionResponse) Reset() {
	*x = CreateClientSessionResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientSessionResponse) ProtoMessage() {}

func (x *CreateClientSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateClientSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateClientSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateClientSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyClientCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClientCodeRequest) Reset() {
	*x = VerifyClientCodeRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClientCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClientCodeRequest) ProtoMessage() {}

func (x *VerifyClientCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClientCodeRequest.ProtoReflect.Descriptor instead.
func (*VerifyClientCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyClientCodeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VerifyClientCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyClientCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyClientCodeResponse) Reset() {
	*x = VerifyClientCodeResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyClientCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyClientCodeResponse) ProtoMessage() {}

func (x *VerifyClientCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyClientCodeResponse.ProtoReflect.Descriptor instead.
func (*VerifyClientCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *VerifyClientCodeResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *VerifyClientCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Additional message types would be defined here
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *LogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *LogoutResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBusinessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessInfoRequest) Reset() {
	*x = GetBusinessInfoRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessInfoRequest) ProtoMessage() {}

func (x *GetBusinessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessInfoRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetBusinessInfoRequest) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

type GetBusinessInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusinessName  string                 `protobuf:"bytes,1,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessType  string                 `protobuf:"bytes,2,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Timezone      string                 `protobuf:"bytes,3,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Locations     []*Location            `protobuf:"bytes,4,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusinessInfoResponse) Reset() {
	*x = GetBusinessInfoResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusinessInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessInfoResponse) ProtoMessage() {}

func (x *GetBusinessInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessInfoResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetBusinessInfoResponse) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *GetBusinessInfoResponse) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *GetBusinessInfoResponse) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *GetBusinessInfoResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type UpdateBusinessInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessInfoRequest) Reset() {
	*x = UpdateBusinessInfoRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessInfoRequest) ProtoMessage() {}

func (x *UpdateBusinessInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateBusinessInfoRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBusinessInfoRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type UpdateBusinessInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBusinessInfoResponse) Reset() {
	*x = UpdateBusinessInfoResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBusinessInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBusinessInfoResponse) ProtoMessage() {}

func (x *UpdateBusinessInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBusinessInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateBusinessInfoResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateBusinessInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUserProfileRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *GetUserProfileResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileRequest) Reset() {
	*x = UpdateUserProfileRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileRequest) ProtoMessage() {}

func (x *UpdateUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateUserProfileRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserProfileResponse) Reset() {
	*x = UpdateUserProfileResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserProfileResponse) ProtoMessage() {}

func (x *UpdateUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateUserProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *CreateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateUserRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetClientSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSessionRequest) Reset() {
	*x = GetClientSessionRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSessionRequest) ProtoMessage() {}

func (x *GetClientSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSessionRequest.ProtoReflect.Descriptor instead.
func (*GetClientSessionRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *GetClientSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetClientSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientSessionResponse) Reset() {
	*x = GetClientSessionResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientSessionResponse) ProtoMessage() {}

func (x *GetClientSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientSessionResponse.ProtoReflect.Descriptor instead.
func (*GetClientSessionResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetClientSessionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetClientSessionResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetClientSessionResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetClientSessionResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetClientSessionResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type CreateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationRequest) Reset() {
	*x = CreateLocationRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationRequest) ProtoMessage() {}

func (x *CreateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationRequest.ProtoReflect.Descriptor instead.
func (*CreateLocationRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *CreateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type CreateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLocationResponse) Reset() {
	*x = CreateLocationResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLocationResponse) ProtoMessage() {}

func (x *CreateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLocationResponse.ProtoReflect.Descriptor instead.
func (*CreateLocationResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{28}
}

func (x *CreateLocationResponse) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsRequest) Reset() {
	*x = GetLocationsRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsRequest) ProtoMessage() {}

func (x *GetLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetLocationsRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{31}
}

func (x *GetLocationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationsResponse) Reset() {
	*x = GetLocationsResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationsResponse) ProtoMessage() {}

func (x *GetLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetLocationsResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{32}
}

func (x *GetLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type CreateMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Master        *Master                `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterRequest) Reset() {
	*x = CreateMasterRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterRequest) ProtoMessage() {}

func (x *CreateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterRequest.ProtoReflect.Descriptor instead.
func (*CreateMasterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{33}
}

func (x *CreateMasterRequest) GetMaster() *Master {
	if x != nil {
		return x.Master
	}
	return nil
}

type CreateMasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMasterResponse) Reset() {
	*x = CreateMasterResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMasterResponse) ProtoMessage() {}

func (x *CreateMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMasterResponse.ProtoReflect.Descriptor instead.
func (*CreateMasterResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{34}
}

func (x *CreateMasterResponse) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

type UpdateMasterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Master        *Master                `protobuf:"bytes,1,opt,name=master,proto3" json:"master,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasterRequest) Reset() {
	*x = UpdateMasterRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasterRequest) ProtoMessage() {}

func (x *UpdateMasterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasterRequest.ProtoReflect.Descriptor instead.
func (*UpdateMasterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateMasterRequest) GetMaster() *Master {
	if x != nil {
		return x.Master
	}
	return nil
}

type UpdateMasterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMasterResponse) Reset() {
	*x = UpdateMasterResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMasterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMasterResponse) ProtoMessage() {}

func (x *UpdateMasterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMasterResponse.ProtoReflect.Descriptor instead.
func (*UpdateMasterResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{36}
}

func (x *UpdateMasterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetMastersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMastersRequest) Reset() {
	*x = GetMastersRequest{}
	mi := &file_user_service_proto_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMastersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMastersRequest) ProtoMessage() {}

func (x *GetMastersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMastersRequest.ProtoReflect.Descriptor instead.
func (*GetMastersRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{37}
}

func (x *GetMastersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetMastersRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

type GetMastersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Masters       []*Master              `protobuf:"bytes,1,rep,name=masters,proto3" json:"masters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMastersResponse) Reset() {
	*x = GetMastersResponse{}
	mi := &file_user_service_proto_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMastersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMastersResponse) ProtoMessage() {}

func (x *GetMastersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMastersResponse.ProtoReflect.Descriptor instead.
func (*GetMastersResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{38}
}

func (x *GetMastersResponse) GetMasters() []*Master {
	if x != nil {
		return x.Masters
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	ManagerId     string                 `protobuf:"bytes,8,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_user_service_proto_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{39}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Location) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Location) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type Master struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId          string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Bio                 string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	PhotoUrl            string                 `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Specialization      string                 `protobuf:"bytes,7,opt,name=specialization,proto3" json:"specialization,omitempty"`
	ExperienceYears     int32                  `protobuf:"varint,8,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Rating              float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalReviews        int32                  `protobuf:"varint,10,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`
	IsVisible           bool                   `protobuf:"varint,11,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	IsAcceptingBookings bool                   `protobuf:"varint,12,opt,name=is_accepting_bookings,json=isAcceptingBookings,proto3" json:"is_accepting_bookings,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Master) Reset() {
	*x = Master{}
	mi := &file_user_service_proto_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Master) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master) ProtoMessage() {}

func (x *Master) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master.ProtoReflect.Descriptor instead.
func (*Master) Descriptor() ([]byte, []int) {
	return file_user_service_proto_user_proto_rawDescGZIP(), []int{40}
}

func (x *Master) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Master) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Master) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Master) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Master) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Master) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Master) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Master) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *Master) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Master) GetTotalReviews() int32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

func (x *Master) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *Master) GetIsAcceptingBookings() bool {
	if x != nil {
		return x.IsAcceptingBookings
	}
	return false
}

var File_user_service_proto_user_proto protoreflect.FileDescriptor

const file_user_service_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x1duser-service/proto/user.proto\x12\x04user\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"j\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1e\n" +
	"\x04user\x18\x03 \x01(\v2\n" +
	".user.UserR\x04user\"\xfe\x01\n" +
	"\x17RegisterBusinessRequest\x12#\n" +
	"\rbusiness_name\x18\x01 \x01(\tR\fbusinessName\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x1c\n" +
	"\tsubdomain\x18\x03 \x01(\tR\tsubdomain\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\x12\x1f\n" +
	"\vowner_email\x18\x05 \x01(\tR\n" +
	"ownerEmail\x12\x1f\n" +
	"\vowner_phone\x18\x06 \x01(\tR\n" +
	"ownerPhone\x12\x1d\n" +
	"\n" +
	"owner_name\x18\a \x01(\tR\townerName\"Q\n" +
	"\x18RegisterBusinessResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf9\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x06 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\a \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12%\n" +
	"\x0eemail_verified\x18\n" +
	" \x01(\bR\remailVerified\x12%\n" +
	"\x0ephone_verified\x18\v \x01(\bR\rphoneVerified\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\"\\\n" +
	"\x1aCreateClientSessionRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"V\n" +
	"\x1bCreateClientSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x17VerifyClientCodeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"J\n" +
	"\x18VerifyClientCodeResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\",\n" +
	"\x14RefreshTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"%\n" +
	"\rLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x16GetBusinessInfoRequest\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\"\xad\x01\n" +
	"\x17GetBusinessInfoResponse\x12#\n" +
	"\rbusiness_name\x18\x01 \x01(\tR\fbusinessName\x12#\n" +
	"\rbusiness_type\x18\x02 \x01(\tR\fbusinessType\x12\x1a\n" +
	"\btimezone\x18\x03 \x01(\tR\btimezone\x12,\n" +
	"\tlocations\x18\x04 \x03(\v2\x0e.user.LocationR\tlocations\"8\n" +
	"\x19UpdateBusinessInfoRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"6\n" +
	"\x1aUpdateBusinessInfoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15GetUserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"8\n" +
	"\x16GetUserProfileResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\":\n" +
	"\x18UpdateUserProfileRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"5\n" +
	"\x19UpdateUserProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x11CreateUserRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"-\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x11UpdateUserRequest\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\".\n" +
	"\x12UpdateUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"8\n" +
	"\x17GetClientSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x92\x01\n" +
	"\x18GetClientSessionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\"C\n" +
	"\x15CreateLocationRequest\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.user.LocationR\blocation\"9\n" +
	"\x16CreateLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\"C\n" +
	"\x15UpdateLocationRequest\x12*\n" +
	"\blocation\x18\x01 \x01(\v2\x0e.user.LocationR\blocation\"2\n" +
	"\x16UpdateLocationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x13GetLocationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"D\n" +
	"\x14GetLocationsResponse\x12,\n" +
	"\tlocations\x18\x01 \x03(\v2\x0e.user.LocationR\tlocations\";\n" +
	"\x13CreateMasterRequest\x12$\n" +
	"\x06master\x18\x01 \x01(\v2\f.user.MasterR\x06master\"3\n" +
	"\x14CreateMasterResponse\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\";\n" +
	"\x13UpdateMasterRequest\x12$\n" +
	"\x06master\x18\x01 \x01(\v2\f.user.MasterR\x06master\"0\n" +
	"\x14UpdateMasterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Q\n" +
	"\x11GetMastersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\"<\n" +
	"\x12GetMastersResponse\x12&\n" +
	"\amasters\x18\x01 \x03(\v2\f.user.MasterR\amasters\"\xe5\x01\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"manager_id\x18\b \x01(\tR\tmanagerId\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"\x81\x03\n" +
	"\x06Master\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1b\n" +
	"\tphoto_url\x18\x06 \x01(\tR\bphotoUrl\x12&\n" +
	"\x0especialization\x18\a \x01(\tR\x0especialization\x12)\n" +
	"\x10experience_years\x18\b \x01(\x05R\x0fexperienceYears\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12#\n" +
	"\rtotal_reviews\x18\n" +
	" \x01(\x05R\ftotalReviews\x12\x1d\n" +
	"\n" +
	"is_visible\x18\v \x01(\bR\tisVisible\x122\n" +
	"\x15is_accepting_bookings\x18\f \x01(\bR\x13isAcceptingBookings2\x8e\v\n" +
	"\vUserService\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x12E\n" +
	"\fRefreshToken\x12\x19.user.RefreshTokenRequest\x1a\x1a.user.RefreshTokenResponse\x123\n" +
	"\x06Logout\x12\x13.user.LogoutRequest\x1a\x14.user.LogoutResponse\x12Q\n" +
	"\x10RegisterBusiness\x12\x1d.user.RegisterBusinessRequest\x1a\x1e.user.RegisterBusinessResponse\x12N\n" +
	"\x0fGetBusinessInfo\x12\x1c.user.GetBusinessInfoRequest\x1a\x1d.user.GetBusinessInfoResponse\x12W\n" +
	"\x12UpdateBusinessInfo\x12\x1f.user.UpdateBusinessInfoRequest\x1a .user.UpdateBusinessInfoResponse\x12K\n" +
	"\x0eGetUserProfile\x12\x1b.user.GetUserProfileRequest\x1a\x1c.user.GetUserProfileResponse\x12T\n" +
	"\x11UpdateUserProfile\x12\x1e.user.UpdateUserProfileRequest\x1a\x1f.user.UpdateUserProfileResponse\x12?\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12Z\n" +
	"\x13CreateClientSession\x12 .user.CreateClientSessionRequest\x1a!.user.CreateClientSessionResponse\x12Q\n" +
	"\x10VerifyClientCode\x12\x1d.user.VerifyClientCodeRequest\x1a\x1e.user.VerifyClientCodeResponse\x12Q\n" +
	"\x10GetClientSession\x12\x1d.user.GetClientSessionRequest\x1a\x1e.user.GetClientSessionResponse\x12K\n" +
	"\x0eCreateLocation\x12\x1b.user.CreateLocationRequest\x1a\x1c.user.CreateLocationResponse\x12K\n" +
	"\x0eUpdateLocation\x12\x1b.user.UpdateLocationRequest\x1a\x1c.user.UpdateLocationResponse\x12E\n" +
	"\fGetLocations\x12\x19.user.GetLocationsRequest\x1a\x1a.user.GetLocationsResponse\x12E\n" +
	"\fCreateMaster\x12\x19.user.CreateMasterRequest\x1a\x1a.user.CreateMasterResponse\x12E\n" +
	"\fUpdateMaster\x12\x19.user.UpdateMasterRequest\x1a\x1a.user.UpdateMasterResponse\x12?\n" +
	"\n" +
	"GetMasters\x12\x17.user.GetMastersRequest\x1a\x18.user.GetMastersResponseB%Z#booking-platform/user-service/protob\x06proto3"

var (
	file_user_service_proto_user_proto_rawDescOnce sync.Once
	file_user_service_proto_user_proto_rawDescData []byte
)

func file_user_service_proto_user_proto_rawDescGZIP() []byte {
	file_user_service_proto_user_proto_rawDescOnce.Do(func() {
		file_user_service_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_user_proto_rawDesc), len(file_user_service_proto_user_proto_rawDesc)))
	})
	return file_user_service_proto_user_proto_rawDescData
}

var file_user_service_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_user_service_proto_user_proto_goTypes = []any{
	(*LoginRequest)(nil),                // 0: user.LoginRequest
	(*LoginResponse)(nil),               // 1: user.LoginResponse
	(*RegisterBusinessRequest)(nil),     // 2: user.RegisterBusinessRequest
	(*RegisterBusinessResponse)(nil),    // 3: user.RegisterBusinessResponse
	(*User)(nil),                        // 4: user.User
	(*CreateClientSessionRequest)(nil),  // 5: user.CreateClientSessionRequest
	(*CreateClientSessionResponse)(nil), // 6: user.CreateClientSessionResponse
	(*VerifyClientCodeRequest)(nil),     // 7: user.VerifyClientCodeRequest
	(*VerifyClientCodeResponse)(nil),    // 8: user.VerifyClientCodeResponse
	(*RefreshTokenRequest)(nil),         // 9: user.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),        // 10: user.RefreshTokenResponse
	(*LogoutRequest)(nil),               // 11: user.LogoutRequest
	(*LogoutResponse)(nil),              // 12: user.LogoutResponse
	(*GetBusinessInfoRequest)(nil),      // 13: user.GetBusinessInfoRequest
	(*GetBusinessInfoResponse)(nil),     // 14: user.GetBusinessInfoResponse
	(*UpdateBusinessInfoRequest)(nil),   // 15: user.UpdateBusinessInfoRequest
	(*UpdateBusinessInfoResponse)(nil),  // 16: user.UpdateBusinessInfoResponse
	(*GetUserProfileRequest)(nil),       // 17: user.GetUserProfileRequest
	(*GetUserProfileResponse)(nil),      // 18: user.GetUserProfileResponse
	(*UpdateUserProfileRequest)(nil),    // 19: user.UpdateUserProfileRequest
	(*UpdateUserProfileResponse)(nil),   // 20: user.UpdateUserProfileResponse
	(*CreateUserRequest)(nil),           // 21: user.CreateUserRequest
	(*CreateUserResponse)(nil),          // 22: user.CreateUserResponse
	(*UpdateUserRequest)(nil),           // 23: user.UpdateUserRequest
	(*UpdateUserResponse)(nil),          // 24: user.UpdateUserResponse
	(*GetClientSessionRequest)(nil),     // 25: user.GetClientSessionRequest
	(*GetClientSessionResponse)(nil),    // 26: user.GetClientSessionResponse
	(*CreateLocationRequest)(nil),       // 27: user.CreateLocationRequest
	(*CreateLocationResponse)(nil),      // 28: user.CreateLocationResponse
	(*UpdateLocationRequest)(nil),       // 29: user.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),      // 30: user.UpdateLocationResponse
	(*GetLocationsRequest)(nil),         // 31: user.GetLocationsRequest
	(*GetLocationsResponse)(nil),        // 32: user.GetLocationsResponse
	(*CreateMasterRequest)(nil),         // 33: user.CreateMasterRequest
	(*CreateMasterResponse)(nil),        // 34: user.CreateMasterResponse
	(*UpdateMasterRequest)(nil),         // 35: user.UpdateMasterRequest
	(*UpdateMasterResponse)(nil),        // 36: user.UpdateMasterResponse
	(*GetMastersRequest)(nil),           // 37: user.GetMastersRequest
	(*GetMastersResponse)(nil),          // 38: user.GetMastersResponse
	(*Location)(nil),                    // 39: user.Location
	(*Master)(nil),                      // 40: user.Master
}
var file_user_service_proto_user_proto_depIdxs = []int32{
	4,  // 0: user.LoginResponse.user:type_name -> user.User
	39, // 1: user.GetBusinessInfoResponse.locations:type_name -> user.Location
	4,  // 2: user.GetUserProfileResponse.user:type_name -> user.User
	4,  // 3: user.UpdateUserProfileRequest.user:type_name -> user.User
	4,  // 4: user.CreateUserRequest.user:type_name -> user.User
	4,  // 5: user.UpdateUserRequest.user:type_name -> user.User
	39, // 6: user.CreateLocationRequest.location:type_name -> user.Location
	39, // 7: user.UpdateLocationRequest.location:type_name -> user.Location
	39, // 8: user.GetLocationsResponse.locations:type_name -> user.Location
	40, // 9: user.CreateMasterRequest.master:type_name -> user.Master
	40, // 10: user.UpdateMasterRequest.master:type_name -> user.Master
	40, // 11: user.GetMastersResponse.masters:type_name -> user.Master
	0,  // 12: user.UserService.Login:input_type -> user.LoginRequest
	9,  // 13: user.UserService.RefreshToken:input_type -> user.RefreshTokenRequest
	11, // 14: user.UserService.Logout:input_type -> user.LogoutRequest
	2,  // 15: user.UserService.RegisterBusiness:input_type -> user.RegisterBusinessRequest
	13, // 16: user.UserService.GetBusinessInfo:input_type -> user.GetBusinessInfoRequest
	15, // 17: user.UserService.UpdateBusinessInfo:input_type -> user.UpdateBusinessInfoRequest
	17, // 18: user.UserService.GetUserProfile:input_type -> user.GetUserProfileRequest
	19, // 19: user.UserService.UpdateUserProfile:input_type -> user.UpdateUserProfileRequest
	21, // 20: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	23, // 21: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	5,  // 22: user.UserService.CreateClientSession:input_type -> user.CreateClientSessionRequest
	7,  // 23: user.UserService.VerifyClientCode:input_type -> user.VerifyClientCodeRequest
	25, // 24: user.UserService.GetClientSession:input_type -> user.GetClientSessionRequest
	27, // 25: user.UserService.CreateLocation:input_type -> user.CreateLocationRequest
	29, // 26: user.UserService.UpdateLocation:input_type -> user.UpdateLocationRequest
	31, // 27: user.UserService.GetLocations:input_type -> user.GetLocationsRequest
	33, // 28: user.UserService.CreateMaster:input_type -> user.CreateMasterRequest
	35, // 29: user.UserService.UpdateMaster:input_type -> user.UpdateMasterRequest
	37, // 30: user.UserService.GetMasters:input_type -> user.GetMastersRequest
	1,  // 31: user.UserService.Login:output_type -> user.LoginResponse
	10, // 32: user.UserService.RefreshToken:output_type -> user.RefreshTokenResponse
	12, // 33: user.UserService.Logout:output_type -> user.LogoutResponse
	3,  // 34: user.UserService.RegisterBusiness:output_type -> user.RegisterBusinessResponse
	14, // 35: user.UserService.GetBusinessInfo:output_type -> user.GetBusinessInfoResponse
	16, // 36: user.UserService.UpdateBusinessInfo:output_type -> user.UpdateBusinessInfoResponse
	18, // 37: user.UserService.GetUserProfile:output_type -> user.GetUserProfileResponse
	20, // 38: user.UserService.UpdateUserProfile:output_type -> user.UpdateUserProfileResponse
	22, // 39: user.UserService.CreateUser:output_type -> user.CreateUserResponse
	24, // 40: user.UserService.UpdateUser:output_type -> user.UpdateUserResponse
	6,  // 41: user.UserService.CreateClientSession:output_type -> user.CreateClientSessionResponse
	8,  // 42: user.UserService.VerifyClientCode:output_type -> user.VerifyClientCodeResponse
	26, // 43: user.UserService.GetClientSession:output_type -> user.GetClientSessionResponse
	28, // 44: user.UserService.CreateLocation:output_type -> user.CreateLocationResponse
	30, // 45: user.UserService.UpdateLocation:output_type -> user.UpdateLocationResponse
	32, // 46: user.UserService.GetLocations:output_type -> user.GetLocationsResponse
	34, // 47: user.UserService.CreateMaster:output_type -> user.CreateMasterResponse
	36, // 48: user.UserService.UpdateMaster:output_type -> user.UpdateMasterResponse
	38, // 49: user.UserService.GetMasters:output_type -> user.GetMastersResponse
	31, // [31:50] is the sub-list for method output_type
	12, // [12:31] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_user_service_proto_user_proto_init() }
func file_user_service_proto_user_proto_init() {
	if File_user_service_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_user_proto_rawDesc), len(file_user_service_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_user_proto_goTypes,
		DependencyIndexes: file_user_service_proto_user_proto_depIdxs,
		MessageInfos:      file_user_service_proto_user_proto_msgTypes,
	}.Build()
	File_user_service_proto_user_proto = out.File
	file_user_service_proto_user_proto_goTypes = nil
	file_user_service_proto_user_proto_depIdxs = nil
}
