// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: booking-service/proto/booking.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBookingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId      string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MasterId        string                 `protobuf:"bytes,3,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	ServiceId       string                 `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClientSessionId string                 `protobuf:"bytes,5,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	ClientName      string                 `protobuf:"bytes,6,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientEmail     string                 `protobuf:"bytes,7,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientPhone     string                 `protobuf:"bytes,8,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	BookingDate     string                 `protobuf:"bytes,9,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime     string                 `protobuf:"bytes,10,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	ClientNotes     string                 `protobuf:"bytes,11,opt,name=client_notes,json=clientNotes,proto3" json:"client_notes,omitempty"`
	CreatedBy       string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateBookingRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateBookingRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *CreateBookingRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateBookingRequest) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *CreateBookingRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateBookingRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *CreateBookingRequest) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *CreateBookingRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *CreateBookingRequest) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *CreateBookingRequest) GetClientNotes() string {
	if x != nil {
		return x.ClientNotes
	}
	return ""
}

func (x *CreateBookingRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type CreateBookingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BookingId        string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ConfirmationCode string                 `protobuf:"bytes,2,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingResponse) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CreateBookingResponse) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *CreateBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MasterId      string                 `protobuf:"bytes,3,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	ClientEmail   string                 `protobuf:"bytes,4,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	DateFrom      string                 `protobuf:"bytes,6,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,7,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Page          int32                  `protobuf:"varint,8,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,9,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingsRequest) Reset() {
	*x = GetBookingsRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsRequest) ProtoMessage() {}

func (x *GetBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingsRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBookingsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetBookingsRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetBookingsRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *GetBookingsRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *GetBookingsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetBookingsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetBookingsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

func (x *GetBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingsResponse) Reset() {
	*x = GetBookingsResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingsResponse) ProtoMessage() {}

func (x *GetBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingsResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{5}
}

func (x *GetBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetBookingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetBookingsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookingsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UpdateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	BookingDate   string                 `protobuf:"bytes,2,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime   string                 `protobuf:"bytes,3,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	ClientNotes   string                 `protobuf:"bytes,4,opt,name=client_notes,json=clientNotes,proto3" json:"client_notes,omitempty"`
	MasterNotes   string                 `protobuf:"bytes,5,opt,name=master_notes,json=masterNotes,proto3" json:"master_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingRequest) Reset() {
	*x = UpdateBookingRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingRequest) ProtoMessage() {}

func (x *UpdateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *UpdateBookingRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *UpdateBookingRequest) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *UpdateBookingRequest) GetClientNotes() string {
	if x != nil {
		return x.ClientNotes
	}
	return ""
}

func (x *UpdateBookingRequest) GetMasterNotes() string {
	if x != nil {
		return x.MasterNotes
	}
	return ""
}

type UpdateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingResponse) Reset() {
	*x = UpdateBookingResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingResponse) ProtoMessage() {}

func (x *UpdateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CancelledBy   string                 `protobuf:"bytes,3,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CancelBookingRequest) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{9}
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CompleteBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	MasterNotes   string                 `protobuf:"bytes,2,opt,name=master_notes,json=masterNotes,proto3" json:"master_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBookingRequest) Reset() {
	*x = CompleteBookingRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBookingRequest) ProtoMessage() {}

func (x *CompleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBookingRequest.ProtoReflect.Descriptor instead.
func (*CompleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CompleteBookingRequest) GetMasterNotes() string {
	if x != nil {
		return x.MasterNotes
	}
	return ""
}

type CompleteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBookingResponse) Reset() {
	*x = CompleteBookingResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBookingResponse) ProtoMessage() {}

func (x *CompleteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBookingResponse.ProtoReflect.Descriptor instead.
func (*CompleteBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{11}
}

func (x *CompleteBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MasterId      string                 `protobuf:"bytes,3,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,4,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAvailabilityRequest) Reset() {
	*x = CheckAvailabilityRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityRequest) ProtoMessage() {}

func (x *CheckAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{12}
}

func (x *CheckAvailabilityRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CheckAvailabilityRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CheckAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableSlots []*TimeSlot            `protobuf:"bytes,1,rep,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckAvailabilityResponse) Reset() {
	*x = CheckAvailabilityResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailabilityResponse) ProtoMessage() {}

func (x *CheckAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{13}
}

func (x *CheckAvailabilityResponse) GetAvailableSlots() []*TimeSlot {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

type GetMasterScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MasterId      string                 `protobuf:"bytes,1,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,2,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,3,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMasterScheduleRequest) Reset() {
	*x = GetMasterScheduleRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterScheduleRequest) ProtoMessage() {}

func (x *GetMasterScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterScheduleRequest.ProtoReflect.Descriptor instead.
func (*GetMasterScheduleRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{14}
}

func (x *GetMasterScheduleRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *GetMasterScheduleRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetMasterScheduleRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetMasterScheduleResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Bookings       []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	AvailableSlots []*TimeSlot            `protobuf:"bytes,2,rep,name=available_slots,json=availableSlots,proto3" json:"available_slots,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMasterScheduleResponse) Reset() {
	*x = GetMasterScheduleResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMasterScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMasterScheduleResponse) ProtoMessage() {}

func (x *GetMasterScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMasterScheduleResponse.ProtoReflect.Descriptor instead.
func (*GetMasterScheduleResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{15}
}

func (x *GetMasterScheduleResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *GetMasterScheduleResponse) GetAvailableSlots() []*TimeSlot {
	if x != nil {
		return x.AvailableSlots
	}
	return nil
}

type CreateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	BaseDuration  int32                  `protobuf:"varint,6,opt,name=base_duration,json=baseDuration,proto3" json:"base_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{16}
}

func (x *CreateServiceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateServiceRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceRequest) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CreateServiceRequest) GetBaseDuration() int32 {
	if x != nil {
		return x.BaseDuration
	}
	return 0
}

type CreateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceResponse) Reset() {
	*x = CreateServiceResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceResponse) ProtoMessage() {}

func (x *CreateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{17}
}

func (x *CreateServiceResponse) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *CreateServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,5,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	BaseDuration  int32                  `protobuf:"varint,6,opt,name=base_duration,json=baseDuration,proto3" json:"base_duration,omitempty"`
	IsActive      bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *UpdateServiceRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateServiceRequest) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *UpdateServiceRequest) GetBaseDuration() int32 {
	if x != nil {
		return x.BaseDuration
	}
	return 0
}

func (x *UpdateServiceRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UpdateServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceResponse) Reset() {
	*x = UpdateServiceResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceResponse) ProtoMessage() {}

func (x *UpdateServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ActiveOnly    bool                   `protobuf:"varint,4,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesRequest) Reset() {
	*x = GetServicesRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesRequest) ProtoMessage() {}

func (x *GetServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesRequest.ProtoReflect.Descriptor instead.
func (*GetServicesRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{20}
}

func (x *GetServicesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetServicesRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetServicesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetServicesRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type GetServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServicesResponse) Reset() {
	*x = GetServicesResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServicesResponse) ProtoMessage() {}

func (x *GetServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServicesResponse.ProtoReflect.Descriptor instead.
func (*GetServicesResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{21}
}

func (x *GetServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteServiceRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBookingStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MasterId      string                 `protobuf:"bytes,3,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	DateFrom      string                 `protobuf:"bytes,4,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,5,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingStatisticsRequest) Reset() {
	*x = GetBookingStatisticsRequest{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingStatisticsRequest) ProtoMessage() {}

func (x *GetBookingStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetBookingStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{24}
}

func (x *GetBookingStatisticsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetBookingStatisticsRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *GetBookingStatisticsRequest) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *GetBookingStatisticsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *GetBookingStatisticsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type GetBookingStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalBookings     int32                  `protobuf:"varint,1,opt,name=total_bookings,json=totalBookings,proto3" json:"total_bookings,omitempty"`
	CompletedBookings int32                  `protobuf:"varint,2,opt,name=completed_bookings,json=completedBookings,proto3" json:"completed_bookings,omitempty"`
	CancelledBookings int32                  `protobuf:"varint,3,opt,name=cancelled_bookings,json=cancelledBookings,proto3" json:"cancelled_bookings,omitempty"`
	TotalRevenue      float64                `protobuf:"fixed64,4,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	AverageRating     float64                `protobuf:"fixed64,5,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	DailyStats        []*DailyStats          `protobuf:"bytes,6,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetBookingStatisticsResponse) Reset() {
	*x = GetBookingStatisticsResponse{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingStatisticsResponse) ProtoMessage() {}

func (x *GetBookingStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetBookingStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{25}
}

func (x *GetBookingStatisticsResponse) GetTotalBookings() int32 {
	if x != nil {
		return x.TotalBookings
	}
	return 0
}

func (x *GetBookingStatisticsResponse) GetCompletedBookings() int32 {
	if x != nil {
		return x.CompletedBookings
	}
	return 0
}

func (x *GetBookingStatisticsResponse) GetCancelledBookings() int32 {
	if x != nil {
		return x.CancelledBookings
	}
	return 0
}

func (x *GetBookingStatisticsResponse) GetTotalRevenue() float64 {
	if x != nil {
		return x.TotalRevenue
	}
	return 0
}

func (x *GetBookingStatisticsResponse) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *GetBookingStatisticsResponse) GetDailyStats() []*DailyStats {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

type Booking struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId         string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	MasterId           string                 `protobuf:"bytes,4,opt,name=master_id,json=masterId,proto3" json:"master_id,omitempty"`
	ServiceId          string                 `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ClientSessionId    string                 `protobuf:"bytes,6,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	ClientName         string                 `protobuf:"bytes,7,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	ClientEmail        string                 `protobuf:"bytes,8,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientPhone        string                 `protobuf:"bytes,9,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	BookingDate        string                 `protobuf:"bytes,10,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime        string                 `protobuf:"bytes,11,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	Duration           int32                  `protobuf:"varint,12,opt,name=duration,proto3" json:"duration,omitempty"`
	Price              float64                `protobuf:"fixed64,13,opt,name=price,proto3" json:"price,omitempty"`
	Status             string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	ClientNotes        string                 `protobuf:"bytes,15,opt,name=client_notes,json=clientNotes,proto3" json:"client_notes,omitempty"`
	MasterNotes        string                 `protobuf:"bytes,16,opt,name=master_notes,json=masterNotes,proto3" json:"master_notes,omitempty"`
	CancellationReason string                 `protobuf:"bytes,17,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	CancelledBy        string                 `protobuf:"bytes,18,opt,name=cancelled_by,json=cancelledBy,proto3" json:"cancelled_by,omitempty"`
	CancelledAt        string                 `protobuf:"bytes,19,opt,name=cancelled_at,json=cancelledAt,proto3" json:"cancelled_at,omitempty"`
	CreatedBy          string                 `protobuf:"bytes,20,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	ConfirmationCode   string                 `protobuf:"bytes,21,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,22,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,23,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Joined data
	Master        *Master   `protobuf:"bytes,24,opt,name=master,proto3" json:"master,omitempty"`
	Service       *Service  `protobuf:"bytes,25,opt,name=service,proto3" json:"service,omitempty"`
	Location      *Location `protobuf:"bytes,26,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{26}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Booking) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Booking) GetMasterId() string {
	if x != nil {
		return x.MasterId
	}
	return ""
}

func (x *Booking) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Booking) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *Booking) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *Booking) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *Booking) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *Booking) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *Booking) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *Booking) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Booking) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetClientNotes() string {
	if x != nil {
		return x.ClientNotes
	}
	return ""
}

func (x *Booking) GetMasterNotes() string {
	if x != nil {
		return x.MasterNotes
	}
	return ""
}

func (x *Booking) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *Booking) GetCancelledBy() string {
	if x != nil {
		return x.CancelledBy
	}
	return ""
}

func (x *Booking) GetCancelledAt() string {
	if x != nil {
		return x.CancelledAt
	}
	return ""
}

func (x *Booking) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Booking) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *Booking) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Booking) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Booking) GetMaster() *Master {
	if x != nil {
		return x.Master
	}
	return nil
}

func (x *Booking) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *Booking) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

type Service struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId        string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	BasePrice       float64                `protobuf:"fixed64,6,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	BaseDuration    int32                  `protobuf:"varint,7,opt,name=base_duration,json=baseDuration,proto3" json:"base_duration,omitempty"`
	IsActive        bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	PopularityScore int32                  `protobuf:"varint,9,opt,name=popularity_score,json=popularityScore,proto3" json:"popularity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{27}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Service) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Service) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *Service) GetBaseDuration() int32 {
	if x != nil {
		return x.BaseDuration
	}
	return 0
}

func (x *Service) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Service) GetPopularityScore() int32 {
	if x != nil {
		return x.PopularityScore
	}
	return 0
}

type Master struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId            string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LocationId          string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Bio                 string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`
	PhotoUrl            string                 `protobuf:"bytes,6,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	Specialization      string                 `protobuf:"bytes,7,opt,name=specialization,proto3" json:"specialization,omitempty"`
	ExperienceYears     int32                  `protobuf:"varint,8,opt,name=experience_years,json=experienceYears,proto3" json:"experience_years,omitempty"`
	Rating              float64                `protobuf:"fixed64,9,opt,name=rating,proto3" json:"rating,omitempty"`
	TotalReviews        int32                  `protobuf:"varint,10,opt,name=total_reviews,json=totalReviews,proto3" json:"total_reviews,omitempty"`
	IsVisible           bool                   `protobuf:"varint,11,opt,name=is_visible,json=isVisible,proto3" json:"is_visible,omitempty"`
	IsAcceptingBookings bool                   `protobuf:"varint,12,opt,name=is_accepting_bookings,json=isAcceptingBookings,proto3" json:"is_accepting_bookings,omitempty"`
	User                *User                  `protobuf:"bytes,13,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Master) Reset() {
	*x = Master{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Master) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Master) ProtoMessage() {}

func (x *Master) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Master.ProtoReflect.Descriptor instead.
func (*Master) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{28}
}

func (x *Master) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Master) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Master) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Master) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Master) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *Master) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

func (x *Master) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *Master) GetExperienceYears() int32 {
	if x != nil {
		return x.ExperienceYears
	}
	return 0
}

func (x *Master) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Master) GetTotalReviews() int32 {
	if x != nil {
		return x.TotalReviews
	}
	return 0
}

func (x *Master) GetIsVisible() bool {
	if x != nil {
		return x.IsVisible
	}
	return false
}

func (x *Master) GetIsAcceptingBookings() bool {
	if x != nil {
		return x.IsAcceptingBookings
	}
	return false
}

func (x *Master) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	IsActive      bool                   `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{29}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Location) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	FirstName     string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{30}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type TimeSlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     string                 `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsAvailable   bool                   `protobuf:"varint,3,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeSlot) Reset() {
	*x = TimeSlot{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeSlot) ProtoMessage() {}

func (x *TimeSlot) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeSlot.ProtoReflect.Descriptor instead.
func (*TimeSlot) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{31}
}

func (x *TimeSlot) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TimeSlot) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TimeSlot) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type DailyStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	BookingsCount int32                  `protobuf:"varint,2,opt,name=bookings_count,json=bookingsCount,proto3" json:"bookings_count,omitempty"`
	Revenue       float64                `protobuf:"fixed64,3,opt,name=revenue,proto3" json:"revenue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStats) Reset() {
	*x = DailyStats{}
	mi := &file_booking_service_proto_booking_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStats) ProtoMessage() {}

func (x *DailyStats) ProtoReflect() protoreflect.Message {
	mi := &file_booking_service_proto_booking_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStats.ProtoReflect.Descriptor instead.
func (*DailyStats) Descriptor() ([]byte, []int) {
	return file_booking_service_proto_booking_proto_rawDescGZIP(), []int{32}
}

func (x *DailyStats) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStats) GetBookingsCount() int32 {
	if x != nil {
		return x.BookingsCount
	}
	return 0
}

func (x *DailyStats) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

var File_booking_service_proto_booking_proto protoreflect.FileDescriptor

const file_booking_service_proto_booking_proto_rawDesc = "" +
	"\n" +
	"#booking-service/proto/booking.proto\x12\abooking\"\xab\x03\n" +
	"\x14CreateBookingRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tmaster_id\x18\x03 \x01(\tR\bmasterId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\tR\tserviceId\x12*\n" +
	"\x11client_session_id\x18\x05 \x01(\tR\x0fclientSessionId\x12\x1f\n" +
	"\vclient_name\x18\x06 \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_email\x18\a \x01(\tR\vclientEmail\x12!\n" +
	"\fclient_phone\x18\b \x01(\tR\vclientPhone\x12!\n" +
	"\fbooking_date\x18\t \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\n" +
	" \x01(\tR\vbookingTime\x12!\n" +
	"\fclient_notes\x18\v \x01(\tR\vclientNotes\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\"}\n" +
	"\x15CreateBookingResponse\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12+\n" +
	"\x11confirmation_code\x18\x02 \x01(\tR\x10confirmationCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"@\n" +
	"\x12GetBookingResponse\x12*\n" +
	"\abooking\x18\x01 \x01(\v2\x10.booking.BookingR\abooking\"\x8a\x02\n" +
	"\x12GetBookingsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tmaster_id\x18\x03 \x01(\tR\bmasterId\x12!\n" +
	"\fclient_email\x18\x04 \x01(\tR\vclientEmail\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1b\n" +
	"\tdate_from\x18\x06 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\a \x01(\tR\x06dateTo\x12\x12\n" +
	"\x04page\x18\b \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\t \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x13GetBookingsResponse\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xc1\x01\n" +
	"\x14UpdateBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\fbooking_date\x18\x02 \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\x03 \x01(\tR\vbookingTime\x12!\n" +
	"\fclient_notes\x18\x04 \x01(\tR\vclientNotes\x12!\n" +
	"\fmaster_notes\x18\x05 \x01(\tR\vmasterNotes\"1\n" +
	"\x15UpdateBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"p\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12!\n" +
	"\fcancelled_by\x18\x03 \x01(\tR\vcancelledBy\"1\n" +
	"\x15CancelBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Z\n" +
	"\x16CompleteBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\fmaster_notes\x18\x02 \x01(\tR\vmasterNotes\"3\n" +
	"\x17CompleteBookingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa8\x01\n" +
	"\x18CheckAvailabilityRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tmaster_id\x18\x03 \x01(\tR\bmasterId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x04 \x01(\tR\tserviceId\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\"W\n" +
	"\x19CheckAvailabilityResponse\x12:\n" +
	"\x0favailable_slots\x18\x01 \x03(\v2\x11.booking.TimeSlotR\x0eavailableSlots\"m\n" +
	"\x18GetMasterScheduleRequest\x12\x1b\n" +
	"\tmaster_id\x18\x01 \x01(\tR\bmasterId\x12\x1b\n" +
	"\tdate_from\x18\x02 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x03 \x01(\tR\x06dateTo\"\x85\x01\n" +
	"\x19GetMasterScheduleResponse\x12,\n" +
	"\bbookings\x18\x01 \x03(\v2\x10.booking.BookingR\bbookings\x12:\n" +
	"\x0favailable_slots\x18\x02 \x03(\v2\x11.booking.TimeSlotR\x0eavailableSlots\"\xc9\x01\n" +
	"\x14CreateServiceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\x01R\tbasePrice\x12#\n" +
	"\rbase_duration\x18\x06 \x01(\x05R\fbaseDuration\"P\n" +
	"\x15CreateServiceResponse\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe8\x01\n" +
	"\x14UpdateServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"base_price\x18\x05 \x01(\x01R\tbasePrice\x12#\n" +
	"\rbase_duration\x18\x06 \x01(\x05R\fbaseDuration\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\"1\n" +
	"\x15UpdateServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x12GetServicesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1f\n" +
	"\vactive_only\x18\x04 \x01(\bR\n" +
	"activeOnly\"C\n" +
	"\x13GetServicesResponse\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.booking.ServiceR\bservices\"5\n" +
	"\x14DeleteServiceRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\"1\n" +
	"\x15DeleteServiceResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xae\x01\n" +
	"\x1bGetBookingStatisticsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tmaster_id\x18\x03 \x01(\tR\bmasterId\x12\x1b\n" +
	"\tdate_from\x18\x04 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x05 \x01(\tR\x06dateTo\"\xa5\x02\n" +
	"\x1cGetBookingStatisticsResponse\x12%\n" +
	"\x0etotal_bookings\x18\x01 \x01(\x05R\rtotalBookings\x12-\n" +
	"\x12completed_bookings\x18\x02 \x01(\x05R\x11completedBookings\x12-\n" +
	"\x12cancelled_bookings\x18\x03 \x01(\x05R\x11cancelledBookings\x12#\n" +
	"\rtotal_revenue\x18\x04 \x01(\x01R\ftotalRevenue\x12%\n" +
	"\x0eaverage_rating\x18\x05 \x01(\x01R\raverageRating\x124\n" +
	"\vdaily_stats\x18\x06 \x03(\v2\x13.booking.DailyStatsR\n" +
	"dailyStats\"\x81\a\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x1b\n" +
	"\tmaster_id\x18\x04 \x01(\tR\bmasterId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x05 \x01(\tR\tserviceId\x12*\n" +
	"\x11client_session_id\x18\x06 \x01(\tR\x0fclientSessionId\x12\x1f\n" +
	"\vclient_name\x18\a \x01(\tR\n" +
	"clientName\x12!\n" +
	"\fclient_email\x18\b \x01(\tR\vclientEmail\x12!\n" +
	"\fclient_phone\x18\t \x01(\tR\vclientPhone\x12!\n" +
	"\fbooking_date\x18\n" +
	" \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\v \x01(\tR\vbookingTime\x12\x1a\n" +
	"\bduration\x18\f \x01(\x05R\bduration\x12\x14\n" +
	"\x05price\x18\r \x01(\x01R\x05price\x12\x16\n" +
	"\x06status\x18\x0e \x01(\tR\x06status\x12!\n" +
	"\fclient_notes\x18\x0f \x01(\tR\vclientNotes\x12!\n" +
	"\fmaster_notes\x18\x10 \x01(\tR\vmasterNotes\x12/\n" +
	"\x13cancellation_reason\x18\x11 \x01(\tR\x12cancellationReason\x12!\n" +
	"\fcancelled_by\x18\x12 \x01(\tR\vcancelledBy\x12!\n" +
	"\fcancelled_at\x18\x13 \x01(\tR\vcancelledAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x14 \x01(\tR\tcreatedBy\x12+\n" +
	"\x11confirmation_code\x18\x15 \x01(\tR\x10confirmationCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x16 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x17 \x01(\tR\tupdatedAt\x12'\n" +
	"\x06master\x18\x18 \x01(\v2\x0f.booking.MasterR\x06master\x12*\n" +
	"\aservice\x18\x19 \x01(\v2\x10.booking.ServiceR\aservice\x12-\n" +
	"\blocation\x18\x1a \x01(\v2\x11.booking.LocationR\blocation\"\x94\x02\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"base_price\x18\x06 \x01(\x01R\tbasePrice\x12#\n" +
	"\rbase_duration\x18\a \x01(\x05R\fbaseDuration\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\x12)\n" +
	"\x10popularity_score\x18\t \x01(\x05R\x0fpopularityScore\"\xa4\x03\n" +
	"\x06Master\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\x12\x1b\n" +
	"\tphoto_url\x18\x06 \x01(\tR\bphotoUrl\x12&\n" +
	"\x0especialization\x18\a \x01(\tR\x0especialization\x12)\n" +
	"\x10experience_years\x18\b \x01(\x05R\x0fexperienceYears\x12\x16\n" +
	"\x06rating\x18\t \x01(\x01R\x06rating\x12#\n" +
	"\rtotal_reviews\x18\n" +
	" \x01(\x05R\ftotalReviews\x12\x1d\n" +
	"\n" +
	"is_visible\x18\v \x01(\bR\tisVisible\x122\n" +
	"\x15is_accepting_bookings\x18\f \x01(\bR\x13isAcceptingBookings\x12!\n" +
	"\x04user\x18\r \x01(\v2\r.booking.UserR\x04user\"\xc6\x01\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1b\n" +
	"\tis_active\x18\b \x01(\bR\bisActive\"\x92\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"g\n" +
	"\bTimeSlot\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\tR\aendTime\x12!\n" +
	"\fis_available\x18\x03 \x01(\bR\visAvailable\"a\n" +
	"\n" +
	"DailyStats\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12%\n" +
	"\x0ebookings_count\x18\x02 \x01(\x05R\rbookingsCount\x12\x18\n" +
	"\arevenue\x18\x03 \x01(\x01R\arevenue2\xbe\b\n" +
	"\x0eBookingService\x12N\n" +
	"\rCreateBooking\x12\x1d.booking.CreateBookingRequest\x1a\x1e.booking.CreateBookingResponse\x12E\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x1b.booking.GetBookingResponse\x12H\n" +
	"\vGetBookings\x12\x1b.booking.GetBookingsRequest\x1a\x1c.booking.GetBookingsResponse\x12N\n" +
	"\rUpdateBooking\x12\x1d.booking.UpdateBookingRequest\x1a\x1e.booking.UpdateBookingResponse\x12N\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponse\x12T\n" +
	"\x0fCompleteBooking\x12\x1f.booking.CompleteBookingRequest\x1a .booking.CompleteBookingResponse\x12Z\n" +
	"\x11CheckAvailability\x12!.booking.CheckAvailabilityRequest\x1a\".booking.CheckAvailabilityResponse\x12Z\n" +
	"\x11GetMasterSchedule\x12!.booking.GetMasterScheduleRequest\x1a\".booking.GetMasterScheduleResponse\x12N\n" +
	"\rCreateService\x12\x1d.booking.CreateServiceRequest\x1a\x1e.booking.CreateServiceResponse\x12N\n" +
	"\rUpdateService\x12\x1d.booking.UpdateServiceRequest\x1a\x1e.booking.UpdateServiceResponse\x12H\n" +
	"\vGetServices\x12\x1b.booking.GetServicesRequest\x1a\x1c.booking.GetServicesResponse\x12N\n" +
	"\rDeleteService\x12\x1d.booking.DeleteServiceRequest\x1a\x1e.booking.DeleteServiceResponse\x12c\n" +
	"\x14GetBookingStatistics\x12$.booking.GetBookingStatisticsRequest\x1a%.booking.GetBookingStatisticsResponseB(Z&booking-platform/booking-service/protob\x06proto3"

var (
	file_booking_service_proto_booking_proto_rawDescOnce sync.Once
	file_booking_service_proto_booking_proto_rawDescData []byte
)

func file_booking_service_proto_booking_proto_rawDescGZIP() []byte {
	file_booking_service_proto_booking_proto_rawDescOnce.Do(func() {
		file_booking_service_proto_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_service_proto_booking_proto_rawDesc), len(file_booking_service_proto_booking_proto_rawDesc)))
	})
	return file_booking_service_proto_booking_proto_rawDescData
}

var file_booking_service_proto_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_booking_service_proto_booking_proto_goTypes = []any{
	(*CreateBookingRequest)(nil),         // 0: booking.CreateBookingRequest
	(*CreateBookingResponse)(nil),        // 1: booking.CreateBookingResponse
	(*GetBookingRequest)(nil),            // 2: booking.GetBookingRequest
	(*GetBookingResponse)(nil),           // 3: booking.GetBookingResponse
	(*GetBookingsRequest)(nil),           // 4: booking.GetBookingsRequest
	(*GetBookingsResponse)(nil),          // 5: booking.GetBookingsResponse
	(*UpdateBookingRequest)(nil),         // 6: booking.UpdateBookingRequest
	(*UpdateBookingResponse)(nil),        // 7: booking.UpdateBookingResponse
	(*CancelBookingRequest)(nil),         // 8: booking.CancelBookingRequest
	(*CancelBookingResponse)(nil),        // 9: booking.CancelBookingResponse
	(*CompleteBookingRequest)(nil),       // 10: booking.CompleteBookingRequest
	(*CompleteBookingResponse)(nil),      // 11: booking.CompleteBookingResponse
	(*CheckAvailabilityRequest)(nil),     // 12: booking.CheckAvailabilityRequest
	(*CheckAvailabilityResponse)(nil),    // 13: booking.CheckAvailabilityResponse
	(*GetMasterScheduleRequest)(nil),     // 14: booking.GetMasterScheduleRequest
	(*GetMasterScheduleResponse)(nil),    // 15: booking.GetMasterScheduleResponse
	(*CreateServiceRequest)(nil),         // 16: booking.CreateServiceRequest
	(*CreateServiceResponse)(nil),        // 17: booking.CreateServiceResponse
	(*UpdateServiceRequest)(nil),         // 18: booking.UpdateServiceRequest
	(*UpdateServiceResponse)(nil),        // 19: booking.UpdateServiceResponse
	(*GetServicesRequest)(nil),           // 20: booking.GetServicesRequest
	(*GetServicesResponse)(nil),          // 21: booking.GetServicesResponse
	(*DeleteServiceRequest)(nil),         // 22: booking.DeleteServiceRequest
	(*DeleteServiceResponse)(nil),        // 23: booking.DeleteServiceResponse
	(*GetBookingStatisticsRequest)(nil),  // 24: booking.GetBookingStatisticsRequest
	(*GetBookingStatisticsResponse)(nil), // 25: booking.GetBookingStatisticsResponse
	(*Booking)(nil),                      // 26: booking.Booking
	(*Service)(nil),                      // 27: booking.Service
	(*Master)(nil),                       // 28: booking.Master
	(*Location)(nil),                     // 29: booking.Location
	(*User)(nil),                         // 30: booking.User
	(*TimeSlot)(nil),                     // 31: booking.TimeSlot
	(*DailyStats)(nil),                   // 32: booking.DailyStats
}
var file_booking_service_proto_booking_proto_depIdxs = []int32{
	26, // 0: booking.GetBookingResponse.booking:type_name -> booking.Booking
	26, // 1: booking.GetBookingsResponse.bookings:type_name -> booking.Booking
	31, // 2: booking.CheckAvailabilityResponse.available_slots:type_name -> booking.TimeSlot
	26, // 3: booking.GetMasterScheduleResponse.bookings:type_name -> booking.Booking
	31, // 4: booking.GetMasterScheduleResponse.available_slots:type_name -> booking.TimeSlot
	27, // 5: booking.GetServicesResponse.services:type_name -> booking.Service
	32, // 6: booking.GetBookingStatisticsResponse.daily_stats:type_name -> booking.DailyStats
	28, // 7: booking.Booking.master:type_name -> booking.Master
	27, // 8: booking.Booking.service:type_name -> booking.Service
	29, // 9: booking.Booking.location:type_name -> booking.Location
	30, // 10: booking.Master.user:type_name -> booking.User
	0,  // 11: booking.BookingService.CreateBooking:input_type -> booking.CreateBookingRequest
	2,  // 12: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	4,  // 13: booking.BookingService.GetBookings:input_type -> booking.GetBookingsRequest
	6,  // 14: booking.BookingService.UpdateBooking:input_type -> booking.UpdateBookingRequest
	8,  // 15: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	10, // 16: booking.BookingService.CompleteBooking:input_type -> booking.CompleteBookingRequest
	12, // 17: booking.BookingService.CheckAvailability:input_type -> booking.CheckAvailabilityRequest
	14, // 18: booking.BookingService.GetMasterSchedule:input_type -> booking.GetMasterScheduleRequest
	16, // 19: booking.BookingService.CreateService:input_type -> booking.CreateServiceRequest
	18, // 20: booking.BookingService.UpdateService:input_type -> booking.UpdateServiceRequest
	20, // 21: booking.BookingService.GetServices:input_type -> booking.GetServicesRequest
	22, // 22: booking.BookingService.DeleteService:input_type -> booking.DeleteServiceRequest
	24, // 23: booking.BookingService.GetBookingStatistics:input_type -> booking.GetBookingStatisticsRequest
	1,  // 24: booking.BookingService.CreateBooking:output_type -> booking.CreateBookingResponse
	3,  // 25: booking.BookingService.GetBooking:output_type -> booking.GetBookingResponse
	5,  // 26: booking.BookingService.GetBookings:output_type -> booking.GetBookingsResponse
	7,  // 27: booking.BookingService.UpdateBooking:output_type -> booking.UpdateBookingResponse
	9,  // 28: booking.BookingService.CancelBooking:output_type -> booking.CancelBookingResponse
	11, // 29: booking.BookingService.CompleteBooking:output_type -> booking.CompleteBookingResponse
	13, // 30: booking.BookingService.CheckAvailability:output_type -> booking.CheckAvailabilityResponse
	15, // 31: booking.BookingService.GetMasterSchedule:output_type -> booking.GetMasterScheduleResponse
	17, // 32: booking.BookingService.CreateService:output_type -> booking.CreateServiceResponse
	19, // 33: booking.BookingService.UpdateService:output_type -> booking.UpdateServiceResponse
	21, // 34: booking.BookingService.GetServices:output_type -> booking.GetServicesResponse
	23, // 35: booking.BookingService.DeleteService:output_type -> booking.DeleteServiceResponse
	25, // 36: booking.BookingService.GetBookingStatistics:output_type -> booking.GetBookingStatisticsResponse
	24, // [24:37] is the sub-list for method output_type
	11, // [11:24] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_booking_service_proto_booking_proto_init() }
func file_booking_service_proto_booking_proto_init() {
	if File_booking_service_proto_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_service_proto_booking_proto_rawDesc), len(file_booking_service_proto_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_service_proto_booking_proto_goTypes,
		DependencyIndexes: file_booking_service_proto_booking_proto_depIdxs,
		MessageInfos:      file_booking_service_proto_booking_proto_msgTypes,
	}.Build()
	File_booking_service_proto_booking_proto = out.File
	file_booking_service_proto_booking_proto_goTypes = nil
	file_booking_service_proto_booking_proto_depIdxs = nil
}
