// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: notification-service/proto/notification.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TemplateName  string                 `protobuf:"bytes,4,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateData  map[string]string      `protobuf:"bytes,5,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SendEmailRequest) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

func (x *SendEmailRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailResponse) Reset() {
	*x = SendEmailResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailResponse) ProtoMessage() {}

func (x *SendEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailResponse.ProtoReflect.Descriptor instead.
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendEmailResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBookingConfirmationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BookingId        string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientEmail      string                 `protobuf:"bytes,2,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientName       string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BusinessName     string                 `protobuf:"bytes,4,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ServiceName      string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MasterName       string                 `protobuf:"bytes,6,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	BookingDate      string                 `protobuf:"bytes,7,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime      string                 `protobuf:"bytes,8,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	LocationAddress  string                 `protobuf:"bytes,9,opt,name=location_address,json=locationAddress,proto3" json:"location_address,omitempty"`
	ConfirmationCode string                 `protobuf:"bytes,10,opt,name=confirmation_code,json=confirmationCode,proto3" json:"confirmation_code,omitempty"`
	Language         string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendBookingConfirmationRequest) Reset() {
	*x = SendBookingConfirmationRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingConfirmationRequest) ProtoMessage() {}

func (x *SendBookingConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingConfirmationRequest.ProtoReflect.Descriptor instead.
func (*SendBookingConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{2}
}

func (x *SendBookingConfirmationRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetMasterName() string {
	if x != nil {
		return x.MasterName
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetLocationAddress() string {
	if x != nil {
		return x.LocationAddress
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetConfirmationCode() string {
	if x != nil {
		return x.ConfirmationCode
	}
	return ""
}

func (x *SendBookingConfirmationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendBookingConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingConfirmationResponse) Reset() {
	*x = SendBookingConfirmationResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingConfirmationResponse) ProtoMessage() {}

func (x *SendBookingConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingConfirmationResponse.ProtoReflect.Descriptor instead.
func (*SendBookingConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{3}
}

func (x *SendBookingConfirmationResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendBookingConfirmationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBookingReminderRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BookingId       string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientEmail     string                 `protobuf:"bytes,2,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientPhone     string                 `protobuf:"bytes,3,opt,name=client_phone,json=clientPhone,proto3" json:"client_phone,omitempty"`
	ClientName      string                 `protobuf:"bytes,4,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BusinessName    string                 `protobuf:"bytes,5,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ServiceName     string                 `protobuf:"bytes,6,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	MasterName      string                 `protobuf:"bytes,7,opt,name=master_name,json=masterName,proto3" json:"master_name,omitempty"`
	BookingDate     string                 `protobuf:"bytes,8,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime     string                 `protobuf:"bytes,9,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	LocationAddress string                 `protobuf:"bytes,10,opt,name=location_address,json=locationAddress,proto3" json:"location_address,omitempty"`
	Language        string                 `protobuf:"bytes,11,opt,name=language,proto3" json:"language,omitempty"`
	HoursBefore     int32                  `protobuf:"varint,12,opt,name=hours_before,json=hoursBefore,proto3" json:"hours_before,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendBookingReminderRequest) Reset() {
	*x = SendBookingReminderRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingReminderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingReminderRequest) ProtoMessage() {}

func (x *SendBookingReminderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingReminderRequest.ProtoReflect.Descriptor instead.
func (*SendBookingReminderRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendBookingReminderRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SendBookingReminderRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *SendBookingReminderRequest) GetClientPhone() string {
	if x != nil {
		return x.ClientPhone
	}
	return ""
}

func (x *SendBookingReminderRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SendBookingReminderRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *SendBookingReminderRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SendBookingReminderRequest) GetMasterName() string {
	if x != nil {
		return x.MasterName
	}
	return ""
}

func (x *SendBookingReminderRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *SendBookingReminderRequest) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *SendBookingReminderRequest) GetLocationAddress() string {
	if x != nil {
		return x.LocationAddress
	}
	return ""
}

func (x *SendBookingReminderRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *SendBookingReminderRequest) GetHoursBefore() int32 {
	if x != nil {
		return x.HoursBefore
	}
	return 0
}

type SendBookingReminderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EmailMessageId string                 `protobuf:"bytes,1,opt,name=email_message_id,json=emailMessageId,proto3" json:"email_message_id,omitempty"`
	SmsMessageId   string                 `protobuf:"bytes,2,opt,name=sms_message_id,json=smsMessageId,proto3" json:"sms_message_id,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendBookingReminderResponse) Reset() {
	*x = SendBookingReminderResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingReminderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingReminderResponse) ProtoMessage() {}

func (x *SendBookingReminderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingReminderResponse.ProtoReflect.Descriptor instead.
func (*SendBookingReminderResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{5}
}

func (x *SendBookingReminderResponse) GetEmailMessageId() string {
	if x != nil {
		return x.EmailMessageId
	}
	return ""
}

func (x *SendBookingReminderResponse) GetSmsMessageId() string {
	if x != nil {
		return x.SmsMessageId
	}
	return ""
}

func (x *SendBookingReminderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBookingCancellationRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BookingId          string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	ClientEmail        string                 `protobuf:"bytes,2,opt,name=client_email,json=clientEmail,proto3" json:"client_email,omitempty"`
	ClientName         string                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	BusinessName       string                 `protobuf:"bytes,4,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	ServiceName        string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	BookingDate        string                 `protobuf:"bytes,6,opt,name=booking_date,json=bookingDate,proto3" json:"booking_date,omitempty"`
	BookingTime        string                 `protobuf:"bytes,7,opt,name=booking_time,json=bookingTime,proto3" json:"booking_time,omitempty"`
	CancellationReason string                 `protobuf:"bytes,8,opt,name=cancellation_reason,json=cancellationReason,proto3" json:"cancellation_reason,omitempty"`
	Language           string                 `protobuf:"bytes,9,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SendBookingCancellationRequest) Reset() {
	*x = SendBookingCancellationRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingCancellationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingCancellationRequest) ProtoMessage() {}

func (x *SendBookingCancellationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingCancellationRequest.ProtoReflect.Descriptor instead.
func (*SendBookingCancellationRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{6}
}

func (x *SendBookingCancellationRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetClientEmail() string {
	if x != nil {
		return x.ClientEmail
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetBusinessName() string {
	if x != nil {
		return x.BusinessName
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetBookingDate() string {
	if x != nil {
		return x.BookingDate
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetBookingTime() string {
	if x != nil {
		return x.BookingTime
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetCancellationReason() string {
	if x != nil {
		return x.CancellationReason
	}
	return ""
}

func (x *SendBookingCancellationRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendBookingCancellationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBookingCancellationResponse) Reset() {
	*x = SendBookingCancellationResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBookingCancellationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBookingCancellationResponse) ProtoMessage() {}

func (x *SendBookingCancellationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBookingCancellationResponse.ProtoReflect.Descriptor instead.
func (*SendBookingCancellationResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{7}
}

func (x *SendBookingCancellationResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendBookingCancellationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSRequest) Reset() {
	*x = SendSMSRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSRequest) ProtoMessage() {}

func (x *SendSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSRequest.ProtoReflect.Descriptor instead.
func (*SendSMSRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{8}
}

func (x *SendSMSRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendSMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendSMSRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendSMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSMSResponse) Reset() {
	*x = SendSMSResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSMSResponse) ProtoMessage() {}

func (x *SendSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSMSResponse.ProtoReflect.Descriptor instead.
func (*SendSMSResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{9}
}

func (x *SendSMSResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendSMSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendVerificationCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeRequest) Reset() {
	*x = SendVerificationCodeRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeRequest) ProtoMessage() {}

func (x *SendVerificationCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeRequest.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{10}
}

func (x *SendVerificationCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SendVerificationCodeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendVerificationCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendVerificationCodeResponse) Reset() {
	*x = SendVerificationCodeResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendVerificationCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendVerificationCodeResponse) ProtoMessage() {}

func (x *SendVerificationCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendVerificationCodeResponse.ProtoReflect.Descriptor instead.
func (*SendVerificationCodeResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{11}
}

func (x *SendVerificationCodeResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendVerificationCodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueueJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobType       string                 `protobuf:"bytes,1,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	JobData       map[string]string      `protobuf:"bytes,2,rep,name=job_data,json=jobData,proto3" json:"job_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScheduledTime string                 `protobuf:"bytes,3,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	RetryAttempts int32                  `protobuf:"varint,4,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueJobRequest) Reset() {
	*x = QueueJobRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueJobRequest) ProtoMessage() {}

func (x *QueueJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueJobRequest.ProtoReflect.Descriptor instead.
func (*QueueJobRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{12}
}

func (x *QueueJobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *QueueJobRequest) GetJobData() map[string]string {
	if x != nil {
		return x.JobData
	}
	return nil
}

func (x *QueueJobRequest) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

func (x *QueueJobRequest) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

type QueueJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueJobResponse) Reset() {
	*x = QueueJobResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueJobResponse) ProtoMessage() {}

func (x *QueueJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueJobResponse.ProtoReflect.Descriptor instead.
func (*QueueJobResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{13}
}

func (x *QueueJobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *QueueJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{14}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{15}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *GetJobStatusResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *GetJobStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetJobStatusResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SendBulkEmailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*EmailRecipient      `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TemplateName  string                 `protobuf:"bytes,4,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	Language      string                 `protobuf:"bytes,5,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailsRequest) Reset() {
	*x = SendBulkEmailsRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailsRequest) ProtoMessage() {}

func (x *SendBulkEmailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailsRequest.ProtoReflect.Descriptor instead.
func (*SendBulkEmailsRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{16}
}

func (x *SendBulkEmailsRequest) GetRecipients() []*EmailRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendBulkEmailsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendBulkEmailsRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendBulkEmailsRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *SendBulkEmailsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendBulkEmailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueuedCount   int32                  `protobuf:"varint,1,opt,name=queued_count,json=queuedCount,proto3" json:"queued_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkEmailsResponse) Reset() {
	*x = SendBulkEmailsResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkEmailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkEmailsResponse) ProtoMessage() {}

func (x *SendBulkEmailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkEmailsResponse.ProtoReflect.Descriptor instead.
func (*SendBulkEmailsResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{17}
}

func (x *SendBulkEmailsResponse) GetQueuedCount() int32 {
	if x != nil {
		return x.QueuedCount
	}
	return 0
}

func (x *SendBulkEmailsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SendBulkSMSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*SMSRecipient        `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkSMSRequest) Reset() {
	*x = SendBulkSMSRequest{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkSMSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkSMSRequest) ProtoMessage() {}

func (x *SendBulkSMSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkSMSRequest.ProtoReflect.Descriptor instead.
func (*SendBulkSMSRequest) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{18}
}

func (x *SendBulkSMSRequest) GetRecipients() []*SMSRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *SendBulkSMSRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendBulkSMSRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type SendBulkSMSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueuedCount   int32                  `protobuf:"varint,1,opt,name=queued_count,json=queuedCount,proto3" json:"queued_count,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendBulkSMSResponse) Reset() {
	*x = SendBulkSMSResponse{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendBulkSMSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBulkSMSResponse) ProtoMessage() {}

func (x *SendBulkSMSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBulkSMSResponse.ProtoReflect.Descriptor instead.
func (*SendBulkSMSResponse) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{19}
}

func (x *SendBulkSMSResponse) GetQueuedCount() int32 {
	if x != nil {
		return x.QueuedCount
	}
	return 0
}

func (x *SendBulkSMSResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EmailRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TemplateData  map[string]string      `protobuf:"bytes,3,rep,name=template_data,json=templateData,proto3" json:"template_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRecipient) Reset() {
	*x = EmailRecipient{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRecipient) ProtoMessage() {}

func (x *EmailRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRecipient.ProtoReflect.Descriptor instead.
func (*EmailRecipient) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{20}
}

func (x *EmailRecipient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *EmailRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmailRecipient) GetTemplateData() map[string]string {
	if x != nil {
		return x.TemplateData
	}
	return nil
}

type SMSRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSRecipient) Reset() {
	*x = SMSRecipient{}
	mi := &file_notification_service_proto_notification_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSRecipient) ProtoMessage() {}

func (x *SMSRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_notification_service_proto_notification_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSRecipient.ProtoReflect.Descriptor instead.
func (*SMSRecipient) Descriptor() ([]byte, []int) {
	return file_notification_service_proto_notification_proto_rawDescGZIP(), []int{21}
}

func (x *SMSRecipient) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SMSRecipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_notification_service_proto_notification_proto protoreflect.FileDescriptor

const file_notification_service_proto_notification_proto_rawDesc = "" +
	"\n" +
	"-notification-service/proto/notification.proto\x12\fnotification\"\xa9\x02\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12#\n" +
	"\rtemplate_name\x18\x04 \x01(\tR\ftemplateName\x12U\n" +
	"\rtemplate_data\x18\x05 \x03(\v20.notification.SendEmailRequest.TemplateDataEntryR\ftemplateData\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"L\n" +
	"\x11SendEmailResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x03\n" +
	"\x1eSendBookingConfirmationRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\fclient_email\x18\x02 \x01(\tR\vclientEmail\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12#\n" +
	"\rbusiness_name\x18\x04 \x01(\tR\fbusinessName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmaster_name\x18\x06 \x01(\tR\n" +
	"masterName\x12!\n" +
	"\fbooking_date\x18\a \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\b \x01(\tR\vbookingTime\x12)\n" +
	"\x10location_address\x18\t \x01(\tR\x0flocationAddress\x12+\n" +
	"\x11confirmation_code\x18\n" +
	" \x01(\tR\x10confirmationCode\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\"Z\n" +
	"\x1fSendBookingConfirmationResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x03\n" +
	"\x1aSendBookingReminderRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\fclient_email\x18\x02 \x01(\tR\vclientEmail\x12!\n" +
	"\fclient_phone\x18\x03 \x01(\tR\vclientPhone\x12\x1f\n" +
	"\vclient_name\x18\x04 \x01(\tR\n" +
	"clientName\x12#\n" +
	"\rbusiness_name\x18\x05 \x01(\tR\fbusinessName\x12!\n" +
	"\fservice_name\x18\x06 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vmaster_name\x18\a \x01(\tR\n" +
	"masterName\x12!\n" +
	"\fbooking_date\x18\b \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\t \x01(\tR\vbookingTime\x12)\n" +
	"\x10location_address\x18\n" +
	" \x01(\tR\x0flocationAddress\x12\x1a\n" +
	"\blanguage\x18\v \x01(\tR\blanguage\x12!\n" +
	"\fhours_before\x18\f \x01(\x05R\vhoursBefore\"\x87\x01\n" +
	"\x1bSendBookingReminderResponse\x12(\n" +
	"\x10email_message_id\x18\x01 \x01(\tR\x0eemailMessageId\x12$\n" +
	"\x0esms_message_id\x18\x02 \x01(\tR\fsmsMessageId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xde\x02\n" +
	"\x1eSendBookingCancellationRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12!\n" +
	"\fclient_email\x18\x02 \x01(\tR\vclientEmail\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\tR\n" +
	"clientName\x12#\n" +
	"\rbusiness_name\x18\x04 \x01(\tR\fbusinessName\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12!\n" +
	"\fbooking_date\x18\x06 \x01(\tR\vbookingDate\x12!\n" +
	"\fbooking_time\x18\a \x01(\tR\vbookingTime\x12/\n" +
	"\x13cancellation_reason\x18\b \x01(\tR\x12cancellationReason\x12\x1a\n" +
	"\blanguage\x18\t \x01(\tR\blanguage\"Z\n" +
	"\x1fSendBookingCancellationResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x0eSendSMSRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"J\n" +
	"\x0fSendSMSResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\x1bSendVerificationCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"W\n" +
	"\x1cSendVerificationCodeResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfd\x01\n" +
	"\x0fQueueJobRequest\x12\x19\n" +
	"\bjob_type\x18\x01 \x01(\tR\ajobType\x12E\n" +
	"\bjob_data\x18\x02 \x03(\v2*.notification.QueueJobRequest.JobDataEntryR\ajobData\x12%\n" +
	"\x0escheduled_time\x18\x03 \x01(\tR\rscheduledTime\x12%\n" +
	"\x0eretry_attempts\x18\x04 \x01(\x05R\rretryAttempts\x1a:\n" +
	"\fJobDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x10QueueJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xb7\x01\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\xc4\x01\n" +
	"\x15SendBulkEmailsRequest\x12<\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1c.notification.EmailRecipientR\n" +
	"recipients\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12#\n" +
	"\rtemplate_name\x18\x04 \x01(\tR\ftemplateName\x12\x1a\n" +
	"\blanguage\x18\x05 \x01(\tR\blanguage\"U\n" +
	"\x16SendBulkEmailsResponse\x12!\n" +
	"\fqueued_count\x18\x01 \x01(\x05R\vqueuedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x01\n" +
	"\x12SendBulkSMSRequest\x12:\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1a.notification.SMSRecipientR\n" +
	"recipients\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"R\n" +
	"\x13SendBulkSMSResponse\x12!\n" +
	"\fqueued_count\x18\x01 \x01(\x05R\vqueuedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd0\x01\n" +
	"\x0eEmailRecipient\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12S\n" +
	"\rtemplate_data\x18\x03 \x03(\v2..notification.EmailRecipient.TemplateDataEntryR\ftemplateData\x1a?\n" +
	"\x11TemplateDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fSMSRecipient\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xc9\a\n" +
	"\x13NotificationService\x12L\n" +
	"\tSendEmail\x12\x1e.notification.SendEmailRequest\x1a\x1f.notification.SendEmailResponse\x12v\n" +
	"\x17SendBookingConfirmation\x12,.notification.SendBookingConfirmationRequest\x1a-.notification.SendBookingConfirmationResponse\x12j\n" +
	"\x13SendBookingReminder\x12(.notification.SendBookingReminderRequest\x1a).notification.SendBookingReminderResponse\x12v\n" +
	"\x17SendBookingCancellation\x12,.notification.SendBookingCancellationRequest\x1a-.notification.SendBookingCancellationResponse\x12F\n" +
	"\aSendSMS\x12\x1c.notification.SendSMSRequest\x1a\x1d.notification.SendSMSResponse\x12m\n" +
	"\x14SendVerificationCode\x12).notification.SendVerificationCodeRequest\x1a*.notification.SendVerificationCodeResponse\x12I\n" +
	"\bQueueJob\x12\x1d.notification.QueueJobRequest\x1a\x1e.notification.QueueJobResponse\x12U\n" +
	"\fGetJobStatus\x12!.notification.GetJobStatusRequest\x1a\".notification.GetJobStatusResponse\x12[\n" +
	"\x0eSendBulkEmails\x12#.notification.SendBulkEmailsRequest\x1a$.notification.SendBulkEmailsResponse\x12R\n" +
	"\vSendBulkSMS\x12 .notification.SendBulkSMSRequest\x1a!.notification.SendBulkSMSResponseB-Z+booking-platform/notification-service/protob\x06proto3"

var (
	file_notification_service_proto_notification_proto_rawDescOnce sync.Once
	file_notification_service_proto_notification_proto_rawDescData []byte
)

func file_notification_service_proto_notification_proto_rawDescGZIP() []byte {
	file_notification_service_proto_notification_proto_rawDescOnce.Do(func() {
		file_notification_service_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_service_proto_notification_proto_rawDesc), len(file_notification_service_proto_notification_proto_rawDesc)))
	})
	return file_notification_service_proto_notification_proto_rawDescData
}

var file_notification_service_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_notification_service_proto_notification_proto_goTypes = []any{
	(*SendEmailRequest)(nil),                // 0: notification.SendEmailRequest
	(*SendEmailResponse)(nil),               // 1: notification.SendEmailResponse
	(*SendBookingConfirmationRequest)(nil),  // 2: notification.SendBookingConfirmationRequest
	(*SendBookingConfirmationResponse)(nil), // 3: notification.SendBookingConfirmationResponse
	(*SendBookingReminderRequest)(nil),      // 4: notification.SendBookingReminderRequest
	(*SendBookingReminderResponse)(nil),     // 5: notification.SendBookingReminderResponse
	(*SendBookingCancellationRequest)(nil),  // 6: notification.SendBookingCancellationRequest
	(*SendBookingCancellationResponse)(nil), // 7: notification.SendBookingCancellationResponse
	(*SendSMSRequest)(nil),                  // 8: notification.SendSMSRequest
	(*SendSMSResponse)(nil),                 // 9: notification.SendSMSResponse
	(*SendVerificationCodeRequest)(nil),     // 10: notification.SendVerificationCodeRequest
	(*SendVerificationCodeResponse)(nil),    // 11: notification.SendVerificationCodeResponse
	(*QueueJobRequest)(nil),                 // 12: notification.QueueJobRequest
	(*QueueJobResponse)(nil),                // 13: notification.QueueJobResponse
	(*GetJobStatusRequest)(nil),             // 14: notification.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),            // 15: notification.GetJobStatusResponse
	(*SendBulkEmailsRequest)(nil),           // 16: notification.SendBulkEmailsRequest
	(*SendBulkEmailsResponse)(nil),          // 17: notification.SendBulkEmailsResponse
	(*SendBulkSMSRequest)(nil),              // 18: notification.SendBulkSMSRequest
	(*SendBulkSMSResponse)(nil),             // 19: notification.SendBulkSMSResponse
	(*EmailRecipient)(nil),                  // 20: notification.EmailRecipient
	(*SMSRecipient)(nil),                    // 21: notification.SMSRecipient
	nil,                                     // 22: notification.SendEmailRequest.TemplateDataEntry
	nil,                                     // 23: notification.QueueJobRequest.JobDataEntry
	nil,                                     // 24: notification.EmailRecipient.TemplateDataEntry
}
var file_notification_service_proto_notification_proto_depIdxs = []int32{
	22, // 0: notification.SendEmailRequest.template_data:type_name -> notification.SendEmailRequest.TemplateDataEntry
	23, // 1: notification.QueueJobRequest.job_data:type_name -> notification.QueueJobRequest.JobDataEntry
	20, // 2: notification.SendBulkEmailsRequest.recipients:type_name -> notification.EmailRecipient
	21, // 3: notification.SendBulkSMSRequest.recipients:type_name -> notification.SMSRecipient
	24, // 4: notification.EmailRecipient.template_data:type_name -> notification.EmailRecipient.TemplateDataEntry
	0,  // 5: notification.NotificationService.SendEmail:input_type -> notification.SendEmailRequest
	2,  // 6: notification.NotificationService.SendBookingConfirmation:input_type -> notification.SendBookingConfirmationRequest
	4,  // 7: notification.NotificationService.SendBookingReminder:input_type -> notification.SendBookingReminderRequest
	6,  // 8: notification.NotificationService.SendBookingCancellation:input_type -> notification.SendBookingCancellationRequest
	8,  // 9: notification.NotificationService.SendSMS:input_type -> notification.SendSMSRequest
	10, // 10: notification.NotificationService.SendVerificationCode:input_type -> notification.SendVerificationCodeRequest
	12, // 11: notification.NotificationService.QueueJob:input_type -> notification.QueueJobRequest
	14, // 12: notification.NotificationService.GetJobStatus:input_type -> notification.GetJobStatusRequest
	16, // 13: notification.NotificationService.SendBulkEmails:input_type -> notification.SendBulkEmailsRequest
	18, // 14: notification.NotificationService.SendBulkSMS:input_type -> notification.SendBulkSMSRequest
	1,  // 15: notification.NotificationService.SendEmail:output_type -> notification.SendEmailResponse
	3,  // 16: notification.NotificationService.SendBookingConfirmation:output_type -> notification.SendBookingConfirmationResponse
	5,  // 17: notification.NotificationService.SendBookingReminder:output_type -> notification.SendBookingReminderResponse
	7,  // 18: notification.NotificationService.SendBookingCancellation:output_type -> notification.SendBookingCancellationResponse
	9,  // 19: notification.NotificationService.SendSMS:output_type -> notification.SendSMSResponse
	11, // 20: notification.NotificationService.SendVerificationCode:output_type -> notification.SendVerificationCodeResponse
	13, // 21: notification.NotificationService.QueueJob:output_type -> notification.QueueJobResponse
	15, // 22: notification.NotificationService.GetJobStatus:output_type -> notification.GetJobStatusResponse
	17, // 23: notification.NotificationService.SendBulkEmails:output_type -> notification.SendBulkEmailsResponse
	19, // 24: notification.NotificationService.SendBulkSMS:output_type -> notification.SendBulkSMSResponse
	15, // [15:25] is the sub-list for method output_type
	5,  // [5:15] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_notification_service_proto_notification_proto_init() }
func file_notification_service_proto_notification_proto_init() {
	if File_notification_service_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_service_proto_notification_proto_rawDesc), len(file_notification_service_proto_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_service_proto_notification_proto_goTypes,
		DependencyIndexes: file_notification_service_proto_notification_proto_depIdxs,
		MessageInfos:      file_notification_service_proto_notification_proto_msgTypes,
	}.Build()
	File_notification_service_proto_notification_proto = out.File
	file_notification_service_proto_notification_proto_goTypes = nil
	file_notification_service_proto_notification_proto_depIdxs = nil
}
